### ISSUE TITLE
[Feature Request] Exceptions raised when wrong `API_PATH` is provided

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1001]
**Problem description**
```python
>>> client.authenticate('org_1-admin', 'password')
Authenticating user org_1-admin...
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "POST /token/user HTTP/1.1" 404 207
Traceback (most recent call last):
  File "/home/frank/miniconda3/envs/v42/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/frank/miniconda3/envs/v42/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/frank/miniconda3/envs/v42/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/frank/miniconda3/envs/v42/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/frank/miniconda3/envs/v42/lib/python3.10/site-packages/vantage6/client/__init__.py", line 127, in authenticate
    auth = super(UserClient, self).authenticate(auth_json,
  File "/home/frank/miniconda3/envs/v42/lib/python3.10/site-packages/vantage6/common/client/client_base.py", line 354, in authenticate
    data = response.json()
  File "/home/frank/miniconda3/envs/v42/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by harmbuisman** [comment]
When can this be picked up?

**Comment by frankcorneliusmartin** [comment]
This has no priority as of now as this is only for improved UX. Any reason you need it now?

**Comment by harmbuisman** [comment]
UX is problematic right now. Not blocking for me right now, just that I ran into this issue again when doing an upgrade, which again took me some time to figure out.

**Comment by bartvanb** [comment]
Since you're running into it multiple times and it shouldn't be too much work, I think it would be good to solve this on shorter term. I have added it to the sprint board so that we will release it with the next version.
