### ISSUE TITLE
[Bug] Squid Proxy 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1054]
**Describe the bug**
When the VPN is not connected and a Squid proxy (whitelisting) is enabled the task crashed before starting. This happens here:
https://github.com/vantage6/vantage6/blob/fdaf7c3dcb653f89fd74f3ebb4d2cce3c80516ef/vantage6-node/vantage6/node/docker/task_manager.py#L478-L485

Most likely the `vpn_manager` is initialized even when the VPN feature is disabled but no subnet is assigned. In the node the following logs appear: 

```bash
2024-02-19 15:40:25 - docker_manager - WARNING  - All docker images are allowed on this Node!
2024-02-19 15:40:25 - task (96)      - DEBUG    - prepare IO files in docker volume
2024-02-19 15:40:25 - task (96)      - DEBUG    - volumes: {'vantage6-idea4rc-user-66-tmpvol': {'bind': '/mnt/tmp', 'mode': 'rw'}, 'vantage6-idea4rc-user-vol': {'bind': '/mnt/data', 'mode': 'rw'}}
2024-02-19 15:40:25 - node           - ERROR    - sequence item 0: expected str instance, NoneType found
Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 988, in run_forever
    self.__start_task(taskresult)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 349, in __start_task
    task_status, vpn_ports = self.__docker.run(
  File "/vantage6/vantage6-node/vantage6/node/docker/docker_manager.py", line 461, in run
    vpn_ports = task.run(
  File "/vantage6/vantage6-node/vantage6/node/docker/task_manager.py", line 242, in run
    self.environment_variables = self._setup_environment_vars(
  File "/vantage6/vantage6-node/vantage6/node/docker/task_manager.py", line 488, in _setup_environment_vars
    environment_variables["NO_PROXY"] = ", ".join(no_proxy)
TypeError: sequence item 0: expected str instance, NoneType found
2024-02-19 15:40:25 - node           - INFO     - Waiting for new tasks....
```

**To Reproduce**
1. Create a node with no VPN connection but with a `whitelisting` block
2. Start task and observe the logs 

**Details**
 - Version 4.2.2

**Comment by bartvanb** [comment]
Fixed by #1055

**Comment by bartvanb** [comment]
Released in 4.2.3
