### ISSUE TITLE
[Bug] Docker volumes, networks, and containers not properly cleaned up

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#1058]
**Describe the bug**
Vantage6 should not leave any dangling docker resources when it is shutdown. However, currently, there are a few items that are not properly cleaned up:

- VPN client containers are not removed on node shutdown
- temporary task volumes are not cleaned up on node shutdown
- squid and ssh volumes are not cleaned up on node shutdown
- node networks are not removed on node shutdown

**Expected behavior**
No dangling docker resources are left

**Details**
 - OS: Windows (docker desktop)

**Comment by bartvanb** [comment]
Not fixed yet in 4.3.0rc1: 
When shutting down a `vdev` network, getting error: 
```
2024-03-08 15:24:33 - docker.auth    - DEBUG    - Found 'credsStore' section
2024-03-08 15:24:33 - urllib3.connectionpool - DEBUG    - http://localhost:None "GET /version HTTP/1.1" 200 None
2024-03-08 15:24:33 - urllib3.connectionpool - DEBUG    - http://localhost:None "GET /v1.43/volumes/vantage6-test430rc1_node_1-user-vol HTTP/1.1" 404 None
Traceback (most recent call last):
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\docker\api\client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localnpipe/v1.43/volumes/vantage6-test430rc1_node_1-user-vol

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\Scripts\v6.exe\__main__.py", line 7, in <module>
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\vantage6\cli\common\decorator.py", line 101, in decorator
    return func(ctx, *extra_args, *args, **kwargs)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\vantage6\cli\dev\stop.py", line 30, in stop_demo_network
    click_ctx.invoke(
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\vantage6\cli\node\stop.py", line 79, in cli_node_stop
    _stop_node(client, container_name, force, system_folders)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\vantage6\cli\node\stop.py", line 120, in _stop_node
    delete_volume_if_exists(docker_client, volume)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\vantage6\common\docker\addons.py", line 522, in delete_volume_if_exists
    volume = client.volumes.get(volume_name)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\docker\models\volumes.py", line 76, in get
    return self.prepare_model(self.client.api.inspect_volume(volume_id))
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\docker\api\volume.py", line 117, in inspect_volume
    return self._result(self._get(url), True)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\docker\api\client.py", line 274, in _result
    self._raise_for_status(response)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\docker\api\client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\430rc1\lib\site-packages\docker\errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localnpipe/v1.43/volumes/vantage6-test430rc1_node_1-user-vol: Not Found ("get vantage6-test430rc1_node_1-user-vol: no such volume")
```
