### ISSUE TITLE
[Change Request] More elaborate error messages for json decoding exceptions

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1085]
I am trying to get my setup working, but am getting json decoding errors. I would opt for Vantage6 catching any decoding exceptions and write to the log what the input data is that is trying to be decoded such that some debugging is possible. E.g. print the type and the content of the data, or a str(input_data)[:30] or something.

```
2024-03-13 09:19:54 - task (4)       - INFO     - info > wrapper for xxx
info > Reading input file /mnt/data/task-000000075/input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/wrap.py", line 52, in wrap_algorithm
    input_data = load_input(input_file)
  File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/wrap.py", line 142, in load_input
    input_data = deserialization.deserialize(fp)
  File "/usr/local/lib/python3.10/site-packages/vantage6/common/client/deserialization.py", line 19, in deserialize
    return json.load(file)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bartvanb** [comment]
@harmbuisman could you specify what the cause of these error would be in the end? That would allow me to specify a better error message.

I am hesitant to print the input data (or part of it) to the logs, as in some cases the input may contain sensitive data (that's when collaboration encryption is recommended)

**Comment by bartvanb** [comment]
It seems we already fixed this in v4.5
