### ISSUE TITLE
[Bug] Aborts (Control-C) are not handled properly when creating a new node config

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1096]
**Describe the bug**
Minor issue. When creating a new node config (`v6 node new`), Control-C only seems to cancel the current question.

**To Reproduce**
```
$ v6 node new --system
? Please enter a configuration-name: testhere
? Enter given api-key: 123123
? The base-URL of the server: http://localhost
? Enter port to which the server listens: 5000
? Path of the api: /api            <Control-C>

Cancelled by user

? Do you want to add a database? (Y/n)            <Control-C>

Cancelled by user

? Which level of logging would you like? (Use arrow keys)            <Control-C>

Cancelled by user

? Do you want to connect to a VPN server? (y/N)            <Control-C>

Cancelled by user

? Do you want to add limit the algorithms allowed to run on your node? This should always be done for production scenari
os. (Y/n)            <Control-C>

Cancelled by user

Traceback (most recent call last):
  File "/opt/vantage6/python-venv/bin/v6", line 8, in <module>
    sys.exit(cli_complete())
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/vantage6/cli/node/new.py", line 50, in cli_node_new_configuration
    cfg_file = configuration_wizard(InstanceType.NODE, name, system_folders)
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/vantage6/cli/configuration_wizard.py", line 445, in configuration_wizard
    config = node_configuration_questionaire(dirs, instance_name)
  File "/opt/vantage6/python-venv/lib/python3.10/site-packages/vantage6/cli/configuration_wizard.py", line 149, in node_configuration_questionaire
    client = NodeClient(config["server_url"], config["port"], config["api_path"])
KeyError: 'server_url'
```

**Expected behavior**
After pressing Control-C a warning with "You are about to exit and information you've provided so far will be lost. Are you sure? Press Control-C again to exit." 

Vantage6 version 4.3.0

**Comment by bartvanb** [comment]
This is a bit more annoying to fix than I expected. The `questionary` package [catches keyboard interrupts](https://github.com/tmbo/questionary/blob/master/questionary/prompt.py#L78) and then returns `None` instead.
So we can use alternative functions like `unsafe_prompt` instead of `prompt` but we do need to adjust every function.

**Comment by bartvanb** [comment]
alias
