### ISSUE TITLE
[Bug] Exception raised when using `client.store....` 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1153]
**Describe the bug**
When `client.store.set()` has not been set, you get the following error on the store clients: 

```python
>>> client.store.user.get(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/FMa1805.36838/Repositories/vantage6/vantage6-client/vantage6/client/filter.py", line 99, in wrapper_filter
    dict_ = func(*args, **kwargs)
  File "/mnt/c/Users/FMa1805.36838/Repositories/vantage6/vantage6-client/vantage6/client/filter.py", line 192, in wrapper_filter
    return func(*args, **kwargs)
  File "/mnt/c/Users/FMa1805.36838/Repositories/vantage6/vantage6-client/vantage6/client/subclients/store_user.py", line 64, in get
    return self.parent.request(
  File "/mnt/c/Users/FMa1805.36838/Repositories/vantage6/vantage6-common/vantage6/common/client/client_base.py", line 227, in request
    url = self.generate_path_to(endpoint, is_for_algorithm_store)
  File "/mnt/c/Users/FMa1805.36838/Repositories/vantage6/vantage6-common/vantage6/common/client/client_base.py", line 171, in generate_path_to
    path = base_path + "/" + endpoint
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Expected behavior**
A human readable error should be returned

**Details**
 - Version 4.3.1

**Comment by bartvanb** [comment]
Fixed by #1158
