### ISSUE TITLE
[Bug] Failure to pull from registries that require authentication

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1168]
**Describe the bug**
Using a registry like [ACR](https://azure.microsoft.com/en-us/products/container-registry), with [credentials in node config file](https://github.com/vantage6/vantage6/blob/version/4.3.2/docs/node/node_config.yaml#L117-L121), I get an error when my node tries to fetch an email from that registry.

**To Reproduce**
1. Host a private image on ACR for example.
2. Create read credentials for it, and put those in [the node config file](https://github.com/vantage6/vantage6/blob/version/4.3.2/docs/node/node_config.yaml#L117-L121).
3. Restart node & attach to logs
4. Send a task to that node using that image
5. Error observed in logs, task fails.
Note: make sure the image you are pulling does not already exist on the machine you are running the node on, as this will make it work because it pulls from the local (existing) image. So if you build and push from the same laptop and run the node there, remember to `docker image rm` the image itself before sending task.

**Expected behavior**
Fetching image and working as when registry without requiring credentials is used 

**Screenshots**
Error log on the node:
```
2024-03-23 22:17:26 - task (137)     - INFO     - Retrieving latest image: 'someacrexampleregistryhere.azurecr.io/examples/example/v6-average-py'
2024-03-23 22:17:26 - task (137)     - DEBUG    - Local image does not exist! someacrexampleregistryhere.azurecr.io/examples/example/v6-average-py
2024-03-23 22:17:26 - task (137)     - WARNING  - Could not construct remote URL, are you using a local image?
2024-03-23 22:17:26 - task (137)     - WARNING  - Or an image from docker hub?
2024-03-23 22:17:26 - task (137)     - WARNING  - We'll make a final attempt when running the image to pull it without any checks...
2024-03-23 22:17:26 - task (137)     - WARNING  - Cannot locate image someacrexampleregistryhere.azurecr.io/examples/example/v6-average-py locally or remotely. Will try to pull it from Docker Hub...
2024-03-23 22:17:27 - task (137)     - ERROR    - Failed to pull image! someacrexampleregistryhere.azurecr.io/examples/example/v6-average-py
2024-03-23 22:17:27 - task (137)     - DEBUG    - 500 Server Error for http+docker://localhost/v1.44/images/create?tag=latest&fromImage=someacrexampleregistryhere.azurecr.io%2Fexamples%2Fexample%2Fv6-average-py: Internal Server Error ("Head "https://someacrexampleregistryhere.azurecr.io/v2/examples/example/v6-average-py/manifests/latest": unauthorized: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}")
2024-03-23 22:17:27 - task (137)     - DEBUG    - Failed to pull image: could not find image
2024-03-23 22:17:27 - task (137)     - ERROR    - Failed to pull image
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.44/images/create?tag=latest&fromImage=someacrexampleregistryhere.azurecr.io%2Fexamples%2Fexample%2Fv6-average-py

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vantage6/vantage6-common/vantage6/common/docker/addons.py", line 309, in pull_if_newer
    docker_client.images.pull(image)
  File "/usr/local/lib/python3.10/site-packages/docker/models/images.py", line 465, in pull
    pull_log = self.client.api.pull(
  File "/usr/local/lib/python3.10/site-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.44/images/create?tag=latest&fromImage=someacrexampleregistryhere.azurecr.io%2Fexamples%2Fexample%2Fv6-average-py: Internal Server Error ("Head "https://someacrexampleregistryhere.azurecr.io/v2/examples/example/v6-average-py/manifests/latest": unauthorized: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/docker/task_manager.py", line 187, in pull
    pull_if_newer(self.docker, self.image, self.log)
  File "/vantage6/vantage6-common/vantage6/common/docker/addons.py", line 314, in pull_if_newer
    raise docker.errors.APIError("Failed to pull image") from e
docker.errors.APIError: Failed to pull image
2024-03-23 22:17:27 - common         - DEBUG    - Sending algorithm run update to server
```

**Details**
- Vantage6 version: 4.3.2
- Linux / Docker 25.0.4

**Comment by lsago** [comment]
I think issue is that logging into registries happens in a different docker client object than the one used to pull images. Quick fix seems to prove this. Will push after making sure fix is sensible.
