### ISSUE TITLE
[Bug] msg node started succesfully when encryption setup fails

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1173]
**Describe the bug**
When the node crashes during startup it claims it started successfully. It seems the message Node started successfully comes too early.

Repro:
- create a node config which has encryption: true, but does not have the specification for the private key file
- start the node vnode start  (without the attach!)
- see the last lines say: Node succesfully started, and use vnode attach to see the logs
- try to attach: nothing happens

**Expected behavior**
Don't say node started succesfully when encryption setup fails
If you run with vnode start --attach you see the error, that should also be printed when leaving out the attach
vnode attach should say: no nodes active if you have no nodes running

**Screenshots**
```
[info ] - Running Docker container
[info ] - Node container was successfully started!
[info ] - To see the logs, run: v6 node attach --name
```

```
(aioc) C:\Users\XYZ\Documents>vnode attach
? Select the node you wish to inspect: vantage6-node-encrypted-user
Traceback (most recent call last):
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\docker\api\client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localnpipe/v1.43/containers/vantage6-node-encrypted-user/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\XYZ\.conda\envs\aioc\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XYZ\.conda\envs\aioc\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\XYZ\.conda\envs\aioc\Scripts\vnode.exe\__main__.py", line 7, in <module>
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\vantage6\cli\node\attach.py", line 46, in cli_node_attach
    container = client.containers.get(name)
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\docker\models\containers.py", line 936, in get
    resp = self.client.api.inspect_container(container_id)
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\docker\utils\decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\docker\api\container.py", line 784, in inspect_container
    return self._result(
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\docker\api\client.py", line 274, in _result
    self._raise_for_status(response)
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\docker\api\client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "C:\Users\XYZ\.conda\envs\aioc\lib\site-packages\docker\errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localnpipe/v1.43/containers/vantage6-node-encrypted-user/json: Not Found ("No such container: vantage6-node-encrypted-user")
```

Version: 4.2.1

**Comment by frankcorneliusmartin** [comment]
Remove *successfully* from the message and add extra explanation to check the node logs

**Comment by bartvanb** [comment]
![image](https://github.com/user-attachments/assets/8f7381ec-62d9-4755-8f7e-8956c3b11942)

I just changed this
