### ISSUE TITLE
[Bug] ⚠️ Missing dependency `pyyaml-include`

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1183]
**Describe the bug**
When you install vantage6 using `pip install vantage6` and then run a command like `v6 server` you get an import error:

```python
Traceback (most recent call last):
  File "/home/frank/miniconda3/envs/alejo/bin/v6", line 5, in <module>
    from vantage6.cli.cli import cli_complete
  File "/home/frank/miniconda3/envs/alejo/lib/python3.10/site-packages/vantage6/cli/cli.py", line 28, in <module>
    from vantage6.cli.algorithm.create import cli_algorithm_create
  File "/home/frank/miniconda3/envs/alejo/lib/python3.10/site-packages/vantage6/cli/algorithm/create.py", line 6, in <module>
    from copier import run_copy
  File "/home/frank/miniconda3/envs/alejo/lib/python3.10/site-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
  File "/home/frank/miniconda3/envs/alejo/lib/python3.10/site-packages/copier/main.py", line 46, in <module>
    from .subproject import Subproject
  File "/home/frank/miniconda3/envs/alejo/lib/python3.10/site-packages/copier/subproject.py", line 15, in <module>
    from .template import Template
  File "/home/frank/miniconda3/envs/alejo/lib/python3.10/site-packages/copier/template.py", line 19, in <module>
    from yamlinclude import YamlIncludeConstructor
ModuleNotFoundError: No module named 'yamlinclude'
```

Installing `pyyaml-include==1.3.2` resolved the issue.

**Comment by frankcorneliusmartin** [comment]
This is the issue from copier: https://github.com/copier-org/copier/issues/1568

**Comment by bartvanb** [comment]
Yes, upgrading was simple, PR is linked now
