### ISSUE TITLE
[Bug] VPN algorithm execution not working if I do not point to an old network_config image

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1245]
To have my VPN working I need to have the following configuration in my node config:
```
images:
  network_config: harbor2.vantage6.ai/infrastructure/vpn-configurator:3.10.3
```

If I do not have it, the logging on starting the node suggests the VPN is connected, but when I try to run the algorithm the node at some point gives the following error:

```
error > Error encountered while calling execute_flower_client: Could not obtain VPN address from response: []
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/wrap.py", line 125, in _run_algorithm_method
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/decorators.py", line 206, in decorator
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/decorators.py", line 107, in decorator
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pluginml/pipeline/pipeline.py", line 1146, in execute_flower_client
    raise RuntimeError(f"Could not obtain VPN address from response: {response}")
RuntimeError: Could not obtain VPN address from response: []
```

I thought the above addition was a temporary workaround and would not be needed with the latest vantage6 version (now I use 4.4). Am I missing something?

**Comment by frankcorneliusmartin** [comment]
Seems to be the same problem as: #724

**Comment by bartvanb** [comment]
Could you add what you are doing in the relevant section of `pipeline.py`? 

> Seems to be very similar as: https://github.com/vantage6/vantage6/issues/724

Could be. @harmbuisman in your node logs, do you see any VPN errors when you start up the node?

**Comment by frankcorneliusmartin** [comment]
This should no longer be an issue as we support EduVPN version 3. If this is still the case, feel free to reopen this issue.
