### ISSUE TITLE
[Change Request] Option to start containers with local image

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#1250]
**Description**
We recently deleted the `pull_if_newer` functionality that allowed to run nodes/servers/stores/... with local image (#1189).

However now (by design) we get:
```
v6 algorithm-store stop --name algo; v6 algorithm-store start --attach --name algo --mount-src . --image newstore
...
...
Traceback (most recent call last):
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\Scripts\v6-script.py", line 33, in <module>
    sys.exit(load_entry_point('vantage6', 'console_scripts', 'v6')())
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\bbe2101.54580\projects\vantage6\vantage6-main\vantage6\vantage6\cli\common\decorator.py", line 101, in decorator
    return func(ctx, *extra_args, *args, **kwargs)
  File "c:\users\bbe2101.54580\projects\vantage6\vantage6-main\vantage6\vantage6\cli\algostore\start.py", line 58, in cli_algo_store_start
    pull_image(docker_client, image)
  File "c:\users\bbe2101.54580\projects\vantage6\vantage6-main\vantage6-common\vantage6\common\docker\addons.py", line 88, in pull_image
    raise docker.errors.APIError("Failed to pull image") from e
docker.errors.APIError: Failed to pull image
```

It would be convenient to come up with a way that developers can still use local infrastructure images for development - for algorithms the new way should be kept I think

**Comment by lsago** [comment]
This would be nice. FWIW, I currently start a local registry and push to it. Something like:
```
$ docker run -d -p 5055:5000 --name registry registry:2
$ make TAG=local REGISTRY=localhost:5055 PLATFORMS=linux/amd64 PUSH_REG=true image
```
