### ISSUE TITLE
[Bug] Algorithm store SSL errors

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1311]
**Describe the bug**
An SSL error happens when the algorithm store communicates with the vantage6 server: 

```
2024-06-10T08:34:13.452795822Z 2024-06-10 08:34:13 - store          - DEBUG    - Received request: GET api/rule?no_pagination=1&username=frank&server_url=https://blueberry.vantage6.ai
2024-06-10T08:34:13.545466955Z 2024-06-10 08:34:13 - store          - ERROR    - Exception occured during request
2024-06-10T08:34:13.545505655Z Traceback (most recent call last):
2024-06-10T08:34:13.545512056Z   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
2024-06-10T08:34:13.545516956Z     rv = self.dispatch_request()
2024-06-10T08:34:13.545521456Z   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
2024-06-10T08:34:13.545526356Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-06-10T08:34:13.545531156Z   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
2024-06-10T08:34:13.545535356Z     resp = resource(*args, **kwargs)
2024-06-10T08:34:13.545539656Z   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 107, in view
2024-06-10T08:34:13.545543456Z     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2024-06-10T08:34:13.545547356Z   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
2024-06-10T08:34:13.545551256Z     resp = meth(*args, **kwargs)
2024-06-10T08:34:13.545555156Z   File "/vantage6/vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py", line 197, in decorator
2024-06-10T08:34:13.545560156Z     response, status = authenticate_with_server(request)
2024-06-10T08:34:13.545564756Z   File "/vantage6/vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py", line 95, in authenticate_with_server
2024-06-10T08:34:13.545578056Z     response = __make_request(url)
2024-06-10T08:34:13.545582456Z   File "/vantage6/vantage6-algorithm-store/vantage6/algorithm/store/resource/__init__.py", line 52, in __make_request
2024-06-10T08:34:13.545586656Z     return requests.post(url, headers=headers)
2024-06-10T08:34:13.545590857Z   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
2024-06-10T08:34:13.545595057Z     return request("post", url, data=data, json=json, **kwargs)
2024-06-10T08:34:13.545598957Z   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
2024-06-10T08:34:13.545602957Z     return session.request(method=method, url=url, **kwargs)
2024-06-10T08:34:13.545607057Z   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
2024-06-10T08:34:13.545611057Z     resp = self.send(prep, **send_kwargs)
2024-06-10T08:34:13.545614857Z   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
2024-06-10T08:34:13.545618857Z     r = adapter.send(request, **kwargs)
2024-06-10T08:34:13.545623257Z   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
2024-06-10T08:34:13.545627957Z     resp = conn.urlopen(
2024-06-10T08:34:13.545634857Z   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
2024-06-10T08:34:13.545639457Z     httplib_response = self._make_request(
2024-06-10T08:34:13.545643657Z   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
2024-06-10T08:34:13.545647557Z     self._validate_conn(conn)
2024-06-10T08:34:13.545651457Z   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
2024-06-10T08:34:13.545655757Z     conn.connect()
2024-06-10T08:34:13.545660357Z   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 406, in connect
2024-06-10T08:34:13.545664757Z     context.verify_mode = resolve_cert_reqs(self.cert_reqs)
2024-06-10T08:34:13.545669057Z   File "/usr/local/lib/python3.10/ssl.py", line 738, in verify_mode
2024-06-10T08:34:13.545673258Z     super(SSLContext, SSLContext).verify_mode.__set__(self, value)
2024-06-10T08:34:13.545677358Z   File "/usr/local/lib/python3.10/ssl.py", line 738, in verify_mode
2024-06-10T08:34:13.545681958Z     super(SSLContext, SSLContext).verify_mode.__set__(self, value)
2024-06-10T08:34:13.545686158Z   File "/usr/local/lib/python3.10/ssl.py", line 738, in verify_mode
2024-06-10T08:34:13.545690158Z     super(SSLContext, SSLContext).verify_mode.__set__(self, value)
2024-06-10T08:34:13.545694458Z   [Previous line repeated 486 more times]
2024-06-10T08:34:13.545705158Z RecursionError: maximum recursion depth exceeded while calling a Python object
2024-06-10T08:34:15.112235101Z 2024-06-10 08:34:15 - store          - DEBUG    - Received request: GET 
2024-06-10T08:34:15.112781408Z 2024-06-10 08:34:15 - store          - DEBUG    - 404 error for route ''
2024-06-10T08:34:15.114014323Z 2024-06-10 08:34:15 - store          - DEBUG    - Received request: GET 
2024-06-10T08:34:15.114544230Z 2024-06-10 08:34:15 - store          - DEBUG    - 404 error for route ''

2024-06-10T08:34:20.623110441Z 2024-06-10 08:34:20 - store          - DEBUG    - Received request: GET api/version
```

Rolling back some dependencies / moving the gevent monkey patch resolved it. Not sure what exactly resolved it. Applied changes: 

```
-Flask-Cors==4.0.1
+Flask-Cors==3.0.10
-requests==2.32.3
+requests==2.31.0
-Werkzeug==3.0.3
+werkzeug==3.0.1
-Flask-Cors==4.0.1
+Flask-Cors==3.0.10
```

and moved the monkey patch to the top in `vantage6-algorithm-store/vantage6/algorithm/store/__init__.py`

Note that this only surfaces in the Azure environment where SSL is configured (so not in your local dev environment)

version: *4.5.3*

**Comment by dskimlinks** [comment]
```
-requests==2.32.3
+requests==2.31.0
```

This one solved it highly likely.

requests `2.32.3` has a hard to reproduce issue when importing SSL lib, up to `2.31.0` everything works.
