### ISSUE TITLE
[Bug] Docker Service Containers are killed on startup

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1346]
**Describe the bug**
 
`docker_service` containers are killed sometimes when you start the node. It seems that this happen when the docker service container is already connected. The node reports the `bye!` message, but somehow the container keeps running. I am very much confused.

I've seen this happen twice now.

```python
2024-06-20 09:20:03 - context        - INFO     - ---------------------------------------------
2024-06-20 09:20:03 - context        - INFO     -  Welcome to
2024-06-20 09:20:03 - context        - INFO     -                   _                     __
2024-06-20 09:20:03 - context        - INFO     -                  | |                   / /
2024-06-20 09:20:03 - context        - INFO     - __   ____ _ _ __ | |_ __ _  __ _  ___ / /_
2024-06-20 09:20:03 - context        - INFO     - \ \ / / _` | '_ \| __/ _` |/ _` |/ _ \ '_ \
2024-06-20 09:20:03 - context        - INFO     -  \ V / (_| | | | | || (_| | (_| |  __/ (_) |
2024-06-20 09:20:03 - context        - INFO     -   \_/ \__,_|_| |_|\__\__,_|\__, |\___|\___/
2024-06-20 09:20:03 - context        - INFO     -                             __/ |
2024-06-20 09:20:03 - context        - INFO     -                            |___/
2024-06-20 09:20:03 - context        - INFO     -
2024-06-20 09:20:03 - context        - INFO     -  --> Join us on Discord! https://discord.gg/rwRvwyK
2024-06-20 09:20:03 - context        - INFO     -  --> Docs: https://docs.vantage6.ai
2024-06-20 09:20:03 - context        - INFO     -  --> Blog: https://vantage6.ai
2024-06-20 09:20:03 - context        - INFO     - ------------------------------------------------------------
2024-06-20 09:20:03 - context        - INFO     - Cite us!
2024-06-20 09:20:03 - context        - INFO     - If you publish your findings obtained using vantage6,
2024-06-20 09:20:03 - context        - INFO     - please cite the proper sources as mentioned in:
2024-06-20 09:20:03 - context        - INFO     - https://vantage6.ai/vantage6/references
2024-06-20 09:20:03 - context        - INFO     - ------------------------------------------------------------
2024-06-20 09:20:03 - context        - INFO     - Started application vantage6
2024-06-20 09:20:03 - context        - INFO     - Current working directory is '/'
2024-06-20 09:20:03 - context        - INFO     - Successfully loaded configuration from '/mnt/config/blueberry.yaml'
2024-06-20 09:20:03 - context        - INFO     - Logging to '/mnt/log/node_user.log'
2024-06-20 09:20:03 - context        - INFO     - Common package version '4.5.3'
2024-06-20 09:20:03 - context        - INFO     - vantage6 version '4.5.3'
2024-06-20 09:20:03 - context        - INFO     - vantage6 version '4.5.3'
2024-06-20 09:20:03 - context        - INFO     - Node package version '4.5.3'
2024-06-20 09:20:03 - node           - INFO     - Connecting server: https://blueberry.vantage6.ai:443
2024-06-20 09:20:03 - node           - DEBUG    - Authenticating
2024-06-20 09:20:03 - common         - DEBUG    - Authenticating node...
2024-06-20 09:20:05 - common         - INFO     - Successfully authenticated
2024-06-20 09:20:05 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/node/5 | None
2024-06-20 09:20:05 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/organization/2 | None
2024-06-20 09:20:06 - node           - INFO     - Node name: main - IKNL
2024-06-20 09:20:06 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/collaboration/1 | None
2024-06-20 09:20:07 - node           - WARNING  - Disabling encryption!
2024-06-20 09:20:07 - node           - INFO     - Setting up proxy server
2024-06-20 09:20:07 - node           - INFO     - Starting proxyserver at 'proxyserver:80'
2024-06-20 09:20:07 - network_man..  - INFO     - Network vantage6-blueberry-user-net already exists! Using existing network
2024-06-20 09:20:07 - node           - INFO     - Setting up VPN client container
2024-06-20 09:20:07 - vpn_manager    - INFO     - Updating VPN images...
2024-06-20 09:20:07 - vpn_manager    - DEBUG    - Pulling Alpine image
2024-06-20 09:20:08 - addons         - DEBUG    - Succeeded to pull image harbor2.vantage6.ai/infrastructure/alpine:4.5
2024-06-20 09:20:08 - vpn_manager    - DEBUG    - Pulling VPN client image
2024-06-20 09:20:09 - addons         - DEBUG    - Succeeded to pull image harbor2.vantage6.ai/infrastructure/vpn-client:4.5
2024-06-20 09:20:09 - vpn_manager    - DEBUG    - Pulling network config image
2024-06-20 09:20:11 - addons         - DEBUG    - Succeeded to pull image harbor2.vantage6.ai/infrastructure/vpn-configurator:4.5
2024-06-20 09:20:11 - vpn_manager    - INFO     - Done updating VPN images
2024-06-20 09:20:11 - vpn_manager    - DEBUG    - Used VPN images:
2024-06-20 09:20:11 - vpn_manager    - DEBUG    -   Alpine: harbor2.vantage6.ai/infrastructure/alpine:4.5
2024-06-20 09:20:11 - vpn_manager    - DEBUG    -   Client: harbor2.vantage6.ai/infrastructure/vpn-client:4.5
2024-06-20 09:20:11 - vpn_manager    - DEBUG    -   Config: harbor2.vantage6.ai/infrastructure/vpn-configurator:4.5
2024-06-20 09:20:11 - node           - WARNING  - VPN subnet is not defined! VPN disabled.
2024-06-20 09:20:11 - node           - INFO     - No SSH tunnels configured
2024-06-20 09:20:11 - node           - INFO     - No squid proxy configured
2024-06-20 09:20:11 - node           - DEBUG    - Setting up the docker manager
2024-06-20 09:20:11 - docker_manager - DEBUG    - Initializing DockerManager
2024-06-20 09:20:11 - docker_manager - DEBUG    - Databases: {'omop': {'uri': 'jdbc:postgresql://omop:5432/omopcdm', 'is_file': False, 'type': 'omop', 'env': {'user': '****', 'password': '****', 'dbms': 'postgresql', 'cdm_database': 'omopcdm', 'cdm_schema': 'omopcdm', 'results_schema': 'results'}}}
2024-06-20 09:20:11 - node           - DEBUG    - Creating websocket connection with the server
2024-06-20 09:20:12 - node           - INFO     - Connected to host=https://blueberry.vantage6.ai on port=443
2024-06-20 09:20:12 - node           - DEBUG    - Starting thread to ping the server to notify this node is online.
2024-06-20 09:20:12 - network_man..  - DEBUG    - Connecting vantage6-blueberry-user to network 'vantage6-blueberry-user-net'
2024-06-20 09:20:12 - node           - INFO     - Linking docker services specified in the configuration
2024-06-20 09:20:12 - network_man..  - DEBUG    - Connecting omop to network 'vantage6-blueberry-user-net'
2024-06-20 09:20:12 - socket         - INFO     - Websocket connection established
2024-06-20 09:20:12 - network_man..  - DEBUG    - Disconnecting vantage6-blueberry-user from network'vantage6-blueberry-user-net'
2024-06-20 09:20:12 - network_man..  - DEBUG    - Deleting network vantage6-blueberry-user-net.
2024-06-20 09:20:12 - addons         - INFO     - Removing container omop in old network
2024-06-20 09:20:12 - addons         - WARNING  - Killing container omop
2024-06-20 09:20:13 - node           - INFO     - Bye!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http+docker://localhost/v1.45/networks/4e3b0b9e4d0e61f2d6fe59a63d6b2899206ff833a8650f14418028ca53b36b4b/connect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/vnode-local", line 33, in <module>
    sys.exit(load_entry_point('vantage6-node', 'console_scripts', 'vnode-local')())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/vantage6/vantage6-node/vantage6/node/cli/node.py", line 226, in cli_node_start
    node.run(ctx)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 1119, in run
    node = Node(ctx)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 102, in __init__
    self.initialize()
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 187, in initialize
    self.link_docker_services()
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 902, in link_docker_services
    self.__docker.link_container_to_network(
  File "/vantage6/vantage6-node/vantage6/node/docker/docker_manager.py", line 676, in link_container_to_network
    self.isolated_network_mgr.connect(
  File "/vantage6/vantage6-common/vantage6/common/docker/network_manager.py", line 135, in connect
    self.network.connect(container_name, aliases=aliases, ipv4_address=ipv4)
  File "/usr/local/lib/python3.10/site-packages/docker/models/networks.py", line 58, in connect
    return self.client.api.connect_container_to_network(
  File "/usr/local/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/docker/api/network.py", line 253, in connect_container_to_network
    self._raise_for_status(res)
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 403 Client Error for http+docker://localhost/v1.45/networks/4e3b0b9e4d0e61f2d6fe59a63d6b2899206ff833a8650f14418028ca53b36b4b/connect: Forbidden ("endpoint with name omop already exists in network vantage6-blueberry-user-net")
2024-06-20 09:20:17 - node           - DEBUG    - SocketIO is not connected, skipping ping
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Details**
 - OS: [e.g. Debian 11, W11]
 - Version [e.g. 3.3.0]
- Docker deamon version

**Additional context**

**Comment by bartvanb** [comment]
Not observed any more, will be changed anyway in v5
