### ISSUE TITLE
[Bug] Error keeps showing: Task is already finished!. Endpoint: /token/container

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1371]
**Describe the bug**
Everytime I start a node in my collaboration I get an error: Task is already finished!. Endpoint: /token/container

**To Reproduce**
2024-07-08 07:36:54 - common         - ERROR    - Server responded with error code: 400
2024-07-08 07:36:54 - common         - ERROR    - msg: Task is already finished!. Endpoint: /token/container
2024-07-08 07:36:54 - common         - INFO     - Refreshing token
2024-07-08 07:36:54 - common         - DEBUG    - Making request: POST | https://cotopaxi.vantage6.ai:443/token/container | None
2024-07-08 07:36:55 - common         - ERROR    - Server responded with error code: 400
2024-07-08 07:36:55 - common         - ERROR    - msg: Task is already finished!. Endpoint: /token/container
2024-07-08 07:36:55 - common         - ERROR    - Nope, refreshing the token didn't fix it.
2024-07-08 07:36:55 - node           - ERROR    - 'container_token'
Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 995, in run_forever
    self.__start_task(taskresult)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 336, in __start_task
    token = token["container_token"]
KeyError: 'container_token'

**Expected behavior**
No error when starting a node.

**Screenshots**
See stacktrace above

**Details**
 - OS: windows
 - Version 4.5.5

**Comment by bartvanb** [comment]
To solve: Make sure that task is not picked up when node is restarted
