### ISSUE TITLE
[Bug] Nodes lose connection and do not reconnect

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1372]
**Describe the bug**
Sometimes we see that nodes do not reconnect.

Example 1
```python
2024-07-04 14:46:50 - socket         - INFO     - New task has been added task_id=1144
2024-07-04 14:46:58 - socket         - INFO     - main - CRN left room collaboration_1
2024-07-04 14:47:02 - socket         - INFO     - Node <main - CRN> joined room <collaboration_1>
2024-07-04 14:47:02 - socket         - INFO     - main - CRN left room collaboration_1
2024-07-04 14:47:02 - socket         - INFO     - Node <main - CRN> joined room <collaboration_1>
2024-07-04 14:47:39 - engineio.client - WARNING  - Unexpected status code 502 in server response, aborting
2024-07-04 14:54:28 - docker_manager - DEBUG    - Run id=1438 is finished
2024-07-04 14:54:28 - common         - DEBUG    - Making request: DELETE | https://blueberry.vantage6.ai:443/port | {'run_id': 1438}
2024-07-04 14:54:29 - node           - INFO     - Sending result (run=1438) to the server!
2024-07-04 14:54:29 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/run/1438 | None
2024-07-04 14:54:30 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/task/1138 | None
2024-07-04 14:54:43 - common         - DEBUG    - Retrieving public key from organization=2
2024-07-04 14:54:43 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/organization/2 | None
2024-07-04 14:54:56 - common         - DEBUG    - Sending algorithm run update to server
2024-07-04 14:54:56 - common         - DEBUG    - Making request: PATCH | https://blueberry.vantage6.ai:443/run/1438 | None
2024-07-04 14:55:09 - common         - ERROR    - Server responded with error code: 502
2024-07-04 14:55:09 - common         - ERROR    - Did not find a message from the server
2024-07-04 14:55:09 - common         - ERROR    - b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Server Error</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>\r\n  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n'
2024-07-04 14:55:09 - common         - INFO     - Refreshing token
2024-07-04 14:55:15 - common         - DEBUG    - Making request: PATCH | https://blueberry.vantage6.ai:443/run/1438 | None
2024-07-04 20:45:15 - common         - INFO     - Refreshing token
2024-07-05 02:35:16 - common         - INFO     - Refreshing token
2024-07-05 08:25:21 - common         - INFO     - Refreshing token
2024-07-05 14:15:22 - common         - INFO     - Refreshing token
2024-07-05 20:05:23 - common         - INFO     - Refreshing token
2024-07-06 01:55:24 - common         - INFO     - Refreshing token
2024-07-06 07:45:25 - common         - INFO     - Refreshing token
2024-07-06 13:35:26 - common         - INFO     - Refreshing token
2024-07-06 19:25:32 - common         - INFO     - Refreshing token
2024-07-07 01:15:33 - common         - INFO     - Refreshing token
2024-07-07 07:05:34 - common         - INFO     - Refreshing token
2024-07-07 12:55:35 - common         - INFO     - Refreshing token
2024-07-07 18:45:36 - common         - INFO     - Refreshing token
2024-07-08 00:35:38 - common         - INFO     - Refreshing token
2024-07-08 06:25:38 - common         - INFO     - Refreshing token
```

Example 2:
```python
2024-07-04 14:51:09 - socket         - INFO     - main - IKNL left room collaboration_1
2024-07-04 14:51:09 - socket         - INFO     - Node <main - IKNL> joined room <collaboration_1>
2024-07-04 14:57:14 - socket         - INFO     - frank left room collaboration_1
2024-07-04 15:05:08 - docker_manager - DEBUG    - Run id=1435 is finished
2024-07-04 15:05:09 - common         - DEBUG    - Making request: DELETE | https://blueberry.vantage6.ai:443/port | {'run_id': 1435}
2024-07-04 15:05:10 - node           - INFO     - Sending result (run=1435) to the server!
2024-07-04 15:05:10 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/run/1435 | None
2024-07-04 15:05:11 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/task/1138 | None
2024-07-04 15:05:14 - common         - DEBUG    - Retrieving public key from organization=2
2024-07-04 15:05:14 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/organization/2 | None
2024-07-04 15:05:22 - common         - DEBUG    - Sending algorithm run update to server
2024-07-04 15:05:22 - common         - DEBUG    - Making request: PATCH | https://blueberry.vantage6.ai:443/run/1435 | None
2024-07-04 20:38:18 - common         - INFO     - Refreshing token
2024-07-05 02:28:33 - common         - INFO     - Refreshing token
2024-07-05 08:18:48 - common         - INFO     - Refreshing token
2024-07-05 14:09:07 - common         - INFO     - Refreshing token
2024-07-05 19:59:24 - common         - INFO     - Refreshing token
2024-07-06 01:49:40 - common         - INFO     - Refreshing token
2024-07-06 07:39:55 - common         - INFO     - Refreshing token
2024-07-06 13:30:11 - common         - INFO     - Refreshing token
2024-07-06 19:20:27 - common         - INFO     - Refreshing token
2024-07-07 01:10:49 - common         - INFO     - Refreshing token
2024-07-07 07:01:05 - common         - INFO     - Refreshing token
2024-07-07 12:51:22 - common         - INFO     - Refreshing token
2024-07-07 18:41:38 - common         - INFO     - Refreshing token
2024-07-08 00:31:55 - common         - INFO     - Refreshing token
2024-07-08 06:22:13 - common         - INFO     - Refreshing token
```

**To Reproduce**
Happens after a while in real networks is the only thing I have right now

**Details**
 - Version: 4.5.3

**Comment by bartvanb** [comment]
Observed on Oracle Linux 8

**Comment by frankcorneliusmartin** [comment]
```yaml
2025-04-30 12:39:08 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/run/5548 | None
2025-04-30 12:39:10 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2025-04-30 12:39:10 - socket         - INFO     - Disconnected from the server
2025-04-30 12:39:11 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2025-04-30 12:39:11 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/task/3436 | None
2025-04-30 12:39:12 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2025-04-30 12:39:12 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2025-04-30 12:39:13 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2025-04-30 12:39:14 - common         - DEBUG    - Retrieving public key from organization=3
2025-04-30 12:39:14 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/organization/3 | None
2025-04-30 12:39:14 - socket         - INFO     - Websocket connection established
2025-04-30 12:39:15 - common         - DEBUG    - Sending algorithm run update to server
2025-04-30 12:39:15 - common         - DEBUG    - Making request: PATCH | https://blueberry.vantage6.ai:443/run/5548 | None
2025-04-30 18:25:48 - common         - INFO     - Refreshing token
2025-05-01 00:15:49 - common         - INFO     - Refreshing token
2025-05-01 06:05:49 - common         - INFO     - Refreshing token
2025-05-01 11:55:50 - common         - INFO     - Refreshing token
2025-05-01 17:45:51 - common         - INFO     - Refreshing token
2025-05-01 23:35:51 - common         - INFO     - Refreshing token
2025-05-02 05:25:52 - common         - INFO     - Refreshing token
```

The interesting thing here is that the **Websocket connection established** is not followed by **(Re)Connected** implying that the `on_sync` ws method is never triggered.

**Comment by frankcorneliusmartin** [comment]
```
2025-03-26 15:55:34 - node           - DEBUG    - Connected to /tasks namespace
2025-03-26 15:55:34 - node           - INFO     - Waiting for new tasks....
2025-03-26 15:55:36 - docker_manager - DEBUG    - Run id=4686 is finished
2025-03-26 15:55:36 - common         - DEBUG    - Making request: DELETE | https://blueberry.vantage6.ai:443/port | {'run_id': 4686}
2025-03-26 15:55:37 - node           - INFO     - Sending result (run=4686) to the server!
2025-03-26 15:55:37 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/run/4686 | None
2025-03-26 15:55:38 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/task/3077 | None
2025-03-26 15:55:40 - common         - DEBUG    - Retrieving public key from organization=3
2025-03-26 15:55:40 - common         - DEBUG    - Making request: GET | https://blueberry.vantage6.ai:443/organization/3 | None
2025-03-26 15:55:41 - common         - DEBUG    - Sending algorithm run update to server
2025-03-26 15:55:41 - common         - DEBUG    - Making request: PATCH | https://blueberry.vantage6.ai:443/run/4686 | None
2025-03-26 21:43:21 - common         - INFO     - Refreshing token
2025-03-27 03:33:22 - common         - INFO     - Refreshing token
2025-03-27 09:23:22 - common         - INFO     - Refreshing token
2025-03-27 14:36:17 - socket         - INFO     - User <frank> joined room <collaboration_1>
2025-03-27 14:37:27 - socket         - INFO     - User <bart-iknl> joined room <collaboration_1>
2025-03-27 14:37:47 - socket         - INFO     - bart-iknl left room collaboration_1
2025-03-27 14:38:03 - socket         - INFO     - frank left room collaboration_1
2025-03-27 14:38:04 - socket         - INFO     - User <frank> joined room <collaboration_1>
2025-03-27 14:39:03 - socket         - INFO     - frank left room collaboration_1
2025-03-27 14:39:05 - socket         - INFO     - User <frank> joined room <collaboration_1>
2025-03-27 14:39:09 - socket         - INFO     - frank left room collaboration_1
2025-03-27 14:39:11 - socket         - INFO     - User <frank> joined room <collaboration_1>
2025-03-27 14:39:18 - socket         - INFO     - frank left room collaboration_1
2025-03-27 15:13:22 - common         - INFO     - Refreshing token
2025-03-27 21:03:23 - common         - INFO     - Refreshing token
2025-03-28 00:13:54 - socket         - INFO     - main - INT left room collaboration_1
2025-03-28 00:13:57 - socket         - INFO     - Node <main - INT> joined room <collaboration_1>
2025-03-28 02:53:23 - common         - INFO     - Refreshing token
```

**Comment by frankcorneliusmartin** [comment]
```yaml
2025-05-02 11:28:07 - socket         - INFO     - User <frank> joined room <collaboration_1>
2025-05-02 11:34:12 - socket         - INFO     - User <frank> joined room <collaboration_1>
Proxy server received status code 403
On attempt 0 to reach https://blueberry.vantage6.ai:443/task/3502, the proxy request raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 127, in make_request
    log.warning("Error messages: %s", response.json())
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
On attempt 0 to reach https://blueberry.vantage6.ai:443/task/3502, the proxy request raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blueberry.vantage6.ai', port=443): Max retries exceeded with url: /task/3502 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 120, in make_request
    response: Response = method(url, json=json, params=params, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blueberry.vantage6.ai', port=443): Max retries exceeded with url: /task/3502 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))
2025-05-02 11:35:10 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2025-05-02 11:35:10 - socket         - INFO     - Disconnected from the server
2025-05-02 11:35:11 - node           - DEBUG    - SocketIO is not connected, skipping ping
2025-05-02 11:35:11 - node           - DEBUG    - SocketIO is not connected, skipping ping
2025-05-02 11:35:11 - node           - DEBUG    - SocketIO is not connected, skipping ping
2025-05-02 11:35:14 - node           - DEBUG    - SocketIO is not connected, skipping ping
2025-05-02 11:35:16 - node           - DEBUG    - SocketIO is not connected, skipping ping
2025-05-02 11:35:18 - node           - DEBUG    - SocketIO is not connected, skipping ping
```

**Comment by frankcorneliusmartin** [comment]
Cursor gave me some suggestions: 

Simultaneous WebSocket Connection Closures: Your logs show multiple consecutive "WebSocket connection was closed, aborting" messages. This suggests that the client is trying to reconnect while previous connections are still in the process of being closed or aborted.
Lack of Exponential Backoff or Retry Strategy: The connect_to_socket() method doesn't implement any retry mechanism with a proper delay between reconnection attempts. It connects immediately and has a static TIME_LIMIT_INITIAL_CONNECTION_WEBSOCKET constant, but doesn't handle the case of repeated reconnection attempts properly.
Socket Connection Overlap: When a disconnect occurs, the current implementation in on_expired_token() disconnects the existing socket, refreshes the token, and immediately tries to reconnect. This could lead to race conditions if the old connection isn't fully terminated before the new one is attempted.
Missing Connection Error Handling: There's no specific handling for connection failures during reconnection attempts. If a reconnection fails, the code doesn't have a clear strategy to retry after a delay.
No State Management During Reconnection: The current code doesn't maintain a clear connection state (connecting, connected, disconnected, reconnecting), which can lead to inconsistent behavior during network hiccups.
Here are my recommendations to fix these issues:
Implement Proper Reconnection Strategy with Exponential Backoff:
Add a retry mechanism with increasing delays between reconnection attempts
Set a maximum number of retries before giving up or alerting the user
Add Better Connection State Management:
Track the socket connection state explicitly (connected, disconnected, connecting)
Only attempt to reconnect when in a fully disconnected state
Add timeouts for connection attempts
Improved Error Handling:
Handle different types of connection errors specifically
Log more detailed information about connection failures
Add a wait period between disconnect and reconnect attempts
Add Connection Health Checks:
Implement a heartbeat mechanism to detect broken connections
Have a fallback plan if socket connections repeatedly fail
Update the Socket.IO and Engine.IO Libraries:
Consider updating the python-socketio (currently 5.7.2) and python-engineio libraries to the latest versions if possible, as newer versions may have better reconnection handling
These changes would help ensure more reliable socket connections and proper handling of network disruptions, preventing the scenario where nodes don't reconnect properly after a disconnect event.

**Comment by bartvanb** [comment]
This is probably no longer relevant by now, at least I haven't seen this in a while. Feel free to reopen
