### ISSUE TITLE
[Feature Request] Python 3.12 compatibility for server tests

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1384]
**Problem description**
My system has Python 3.12 installed, when developing on vantage6, using python 3.12 will result in errors.

**Desired solution**
Running server tests works

**Additional context**
This is just a note for future reference.

**Comment by lsago** [comment]
When running tests..
```
Failed to import test module: tests_server.test_models
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/repos/vantage6/vantage6-server/tests_server/test_models.py", line 8, in <module>
    from vantage6.server.controller.fixture import load
  File "/repos/vantage6/vantage6-server/vantage6/server/__init__.py", line 28, in <module>
    from flasgger import Swagger
  File "/path/to/my/venv/lib/python3.12/site-packages/flasgger/__init__.py", line 10, in <module>
    from .base import Swagger, Flasgger, NO_SANITIZER, BR_SANITIZER, MK_SANITIZER, LazyJSONEncoder  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/venv/lib/python3.12/site-packages/flasgger/base.py", line 36, in <module>
    from .utils import extract_definitions
  File "/path/to/my/venv/lib/python3.12/site-packages/flasgger/utils.py", line 5, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

Solution that works albeit not thoroughly reviewed: bump flasgger to 0.9.7.1

**Comment by lsago** [comment]
Further, when bumping flasgger==0.9.7.1, we hit an error for `vantage6-server/tests_server/test_resources.py`

```
setUpClass (tests_server.test_resources.TestResources) Failed with Error: '<' not supported between instances of 'str' and 'int'
  File "/usr/lib/python3.12/unittest/suite.py", line 166, in _handleClassSetUp
    setUpClass()
  File "/some/path/repos/vantage6/vantage6-server/tests_server/test_resources.py", line 74, in setUpClass
    server = ServerApp(ctx)
             ^^^^^^^^^^^^^^
  File "/some/path/repos/vantage6/vantage6-server/vantage6/server/__init__.py", line 131, in __init__
    self.swagger = Swagger(self.app, template=swagger_template)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/path/repos/vantage6/dev/venv/lib/python3.12/site-packages/flasgger/base.py", line 255, in __init__
    self.init_app(app)
  File "/some/path/repos/vantage6/dev/venv/lib/python3.12/site-packages/flasgger/base.py", line 269, in init_app
    self.register_views(app)
  File "/some/path/repos/vantage6/dev/venv/lib/python3.12/site-packages/flasgger/base.py", line 645, in register_views
    if uiversion < 3:
       ^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
```


Solution:
```diff
diff --git a/vantage6-server/vantage6/server/__init__.py b/vantage6-server/vantage6/server/__init__.py
index 7eccfad6..67eb04cb 100644
--- a/vantage6-server/vantage6/server/__init__.py
+++ b/vantage6-server/vantage6/server/__init__.py
@@ -277,7 +277,7 @@ class ServerApp:
         # Open Api Specification (f.k.a. swagger)
         self.app.config["SWAGGER"] = {
             "title": APPNAME,
-            "uiversion": "3",
+            "uiversion": 3,
             "openapi": "3.0.0",
             "version": __version__,
         }
```
Using int instead of str as shown [here](https://github.com/flasgger/flasgger?tab=readme-ov-file#swagger-ui-and-templates)

**Comment by bartvanb** [comment]
Related #1604

**Comment by bartvanb** [comment]
Duplicate #1315
