### ISSUE TITLE
[Bug] More fool proof yaml handling

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1475]
If I configure policies in my yaml as follows:
policies:
- allowed_algorithms: ^harbor\.vantage6\.ai/plugin/.*

I get an error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/vnode-local", line 33, in <module>
    sys.exit(load_entry_point('vantage6-node', 'console_scripts', 'vnode-local')())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/vantage6/vantage6-node/vantage6/node/cli/node.py", line 226, in cli_node_start
    node.run(ctx)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 1127, in run
    node = Node(ctx)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 102, in __init__
    self.initialize()
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 164, in initialize
    self.__docker = DockerManager(
  File "/vantage6/vantage6-node/vantage6/node/docker/docker_manager.py", line 149, in __init__
    self._policies = self._setup_policies(config)
  File "/vantage6/vantage6-node/vantage6/node/docker/docker_manager.py", line 256, in _setup_policies
    not policies.get(NodePolicy.ALLOWED_ALGORITHMS)
AttributeError: 'list' object has no attribute 'get'
```

It is not so straightforward when to add a - and when to just do a tab/whitespaces. Please make the yaml parsing more foolproof such that it allows for both having the - and having a tab/whitespaces

To fix the above error I just had to remove the -

**Comment by bartvanb** [comment]
What needs to be done for this is a validation of the YAML file with clear errors if it does not follow the required structure
