### ISSUE TITLE
Kill algorithms and nodes remotely

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#167]
Sometimes we want to stop algorithm containers because it entered a never ending loop 

We should introduce three new `socketio` events:

- `on_kill_algorithm` - kills a specific (using an `id`) algorithm container at the node
- `on_kill_all_algorithms` - kills all running algorithm containers
- `on_shutdown` - stops the nodes and their algorithm containers completely

When an algorithm container is killed, the node will see this as if the algorithm crashed. I think this behaviour is fine. In case you want to stop an algorithm container more gracefully, the container itself should receive a kill signal.

**Comment by bartvanb** [comment]
Proposed check list:

- [ ] endpoint to stop a single container via `on_kill_algorithm` socket event
- [ ] endpoint to stop all containers on a node via `on_kill_all_algorithms` socket event
- [ ] endpoint to shutdown a node and all its containers via `on_shutdown` socket event
- [ ] allow a node to shutdown subtasks of the master task it is running itself via the algorithm client
- [ ] allow a user to use all endpoints and generate functions to use them in the client

We should consider how to implement these endpoints. Some ideas
- `/result/<id>/kill` to kill a single task
- `/node/<id>/algorithms/kill` to kill all tasks on a node, or alternatively  `/result/kill/node/<node_id>` 
- Similarly, `/node/<id>/shutdown` to shutdown the node
But this all feels a bit awkward: functionality does not seem to be in logical places. Maybe it would be an idea to create endpoints such as `/kill/result/<id>`, `kill/node/<id>`, `/shutdown/node/<node_id>`

**Comment by bartvanb** [comment]
Maybe have a more flexible endpoint `/kill?params=...` where you can specify which task_id on which node should be killed (or a specific result_id

**Comment by bartvanb** [comment]
Preliminary work is on branch [feature/kill-algorithm-endpoint](https://github.com/vantage6/vantage6/tree/feature/kill-algorithm-endpoint), commit https://github.com/vantage6/vantage6/commit/e7421d3c0568ffaac9c5c0050470eecb95d8fed1. 

It has already been tested that the correct nodes are reached and attempt to kill the appropriate tasks, but no tasks have actually been run yet to check they are successfully killed.

**Comment by bartvanb** [comment]
There is a tricky situation in obtaining active tasks from a node as a user: if the user does an HTTP request to the server API, the server can only obtain the active tasks async via websocket and that can not simply be returned to the user. Two possible solutions to circumvent this:

1. user should connect via websocket to the server, which should determine which rooms the user is allowed to enter. 
2. when the node returns info to the server, it could be saved in the database (ugly solution)

Solution 1 is much preferable, but also tricky to implement in the python client as the async websocket information can easily get lost in notebooks and such. Thus, we'll start by implementing it in the UI.
Note that a socket connections would also be solution for node off/online status (#40)

**Comment by bartvanb** [comment]
Obtaining active tasks should be done simply from the task table: a task that has a `started_at` but not a `finished_at` is running (if the node is online)

**Comment by frankcorneliusmartin** [comment]
When I kill all results:

```python
2023-01-11 12:46:21 - socket         - INFO     - Received instruction to kill task: {'node_id': 8, 'collaboration_id': 1}
2023-01-11 12:46:21 - docker_manager - WARNING  - Received instruction from server to kill all algorithms running on this node. Executing that now...
2023-01-11 12:46:21 - docker_manager - DEBUG    - Killing 1 active task(s)
Exception in thread Thread-39:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 705, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 581, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 637, in _trigger_event
    event, *args)
  File "/usr/local/lib/python3.7/site-packages/socketio/namespace.py", line 18, in trigger_event
    return getattr(self, handler_name)(*args)
  File "/vantage6/vantage6-node/vantage6/node/socket.py", line 125, in on_kill_containers
    killed_ids = self.node_worker_ref.kill_containers(kill_info)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 793, in kill_containers
    org_id=self.server_io.whoami.organization_id, kill_list=kill_list
  File "/vantage6/vantage6-node/vantage6/node/docker/docker_manager.py", line 559, in kill_tasks
    "Killed the following result ids as instructed via socket:"
TypeError: sequence item 0: expected str instance, KilledResult found
```

The task is killed, but I get this exception. It seems like the node is unaffected, as in: still works

**Comment by frankcorneliusmartin** [comment]
Same goes for killing a single task:
```python
client.request(endpoint='kill/task', json={'id':7}, method='post')
```
```python
2023-01-11 12:49:57 - socket         - INFO     - Received instruction to kill task: {'kill_list': [{'task_id': 7, 'result_id': 12, 'organization_id': 2}], 'collaboration_id': 1}
2023-01-11 12:49:57 - docker_manager - INFO     - Killing containers for result_id=12
Exception in thread Thread-48:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 705, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 581, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 637, in _trigger_event
    event, *args)
  File "/usr/local/lib/python3.7/site-packages/socketio/namespace.py", line 18, in trigger_event
    return getattr(self, handler_name)(*args)
  File "/vantage6/vantage6-node/vantage6/node/socket.py", line 130, in on_kill_containers
    'result_id': killed['result_id'],
TypeError: tuple indices must be integers or slices, not str
```

Seems like a type issue?

**Comment by frankcorneliusmartin** [comment]
```python
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 705, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 581, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 637, in _trigger_event
    event, *args)
  File "/usr/local/lib/python3.7/site-packages/socketio/namespace.py", line 18, in trigger_event
    return getattr(self, handler_name)(*args)
  File "/vantage6/vantage6-node/vantage6/node/socket.py", line 125, in on_kill_containers
    killed_ids = self.node_worker_ref.kill_containers(kill_info)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 793, in kill_containers
    org_id=self.server_io.whoami.organization_id, kill_list=kill_list
  File "/vantage6/vantage6-node/vantage6/node/docker/docker_manager.py", line 559, in kill_tasks
    "Killed the following result ids as instructed via socket:"
TypeError: sequence item 0: expected str instance, KilledResult found
```
