### ISSUE TITLE
Error while using configuration wizard

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#217]
While setting up a node (version `3.2.0`) with the configuration wizard I encountered the an error just after filling in the path to the private key file.

I don't know what to make of the error and it seems pretty generic. Could there be a bug in the configuration wizard?

```bash
? Path to private key file: /home/some/path/private.pem
Traceback (most recent call last):
  File "/home/some/path/venv/bin/vnode", line 8, in <module>
    sys.exit(cli_node())
  File "/home/some/path/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/some/path/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main 
    rv = self.invoke(ctx)
  File "/home/some/path/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/some/path/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/some/path/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/some/path/venv/lib/python3.8/site-packages/vantage6/cli/node.py", line 171, in cli_node_new_configuration
    cfg_file = configuration_wizard("node", name, environment, system_folders)
  File "/home/some/path/venv/lib/python3.8/site-packages/vantage6/cli/configuration_wizard.py", line 241, in configuration_wizard
    config_manager.put(environment, config)
  File "/home/some/path/venv/lib/python3.8/site-packages/vantage6/common/configuration_manager.py", line 73, in put
    configuration = self.conf_class(config)
  File "/home/some/path/venv/lib/python3.8/site-packages/vantage6/common/configuration_manager.py", line 14, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/collections/__init__.py", line 999, in __init__
    self.update(dict)
  File "/usr/lib/python3.8/_collections_abc.py", line 832, in update
    self[key] = other[key]
  File "/home/some/path/venv/lib/python3.8/site-packages/vantage6/common/configuration_manager.py", line 24, in __setitem__
    assert schema.is_valid(value), f"Invalid Value! {value} for {schema}"
AssertionError: Invalid Value!  for Schema(And(Use(<class 'str'>), <built-in function len>))
```

**Comment by bartvanb** [comment]
I was able to reproduce this error, and in fact is is not caused by the private key file path. This is just the last configuration option that is filled in before the configuration is evaluated. The error is thrown when the configuration is evaluated and the API key is empty, which is the result of the validator [here](https://github.com/vantage6/vantage6/blob/main/vantage6/vantage6/cli/configuration_manager.py#L34).

I think this can be solved in two ways:
- Allow not specifying the API key in `vnode new`. This would just require the validator in the link above to be adapted
- Clarify the error message. This should then say exactly which value is not allowed for which key (the Schema stuff should not be printed)
We should clarify the error message either way as it could also occur for other configuration keys.

@frankcorneliusmartin is there a specific reason that the API key is not allowed to be empty?

**Comment by dsmits** [comment]
It makes sense to me that it would fail without an api key. Then it would help if the wizard would say so.

I don't remember exactly why I ran the wizard but it was probably because it was the easiest way to create a new configuration file.
Because I'm deploying my vantage stuff with ansible I don't actually use the wizard for the real node, but I used it to create a template for the config file.

**Comment by bartvanb** [comment]
I just added a [commit](https://github.com/vantage6/vantage6/commit/49342b47d484302e6651387d860146b81672b14a) that improves the error message.

I'm not creating a PR yet because I'd like to be consistent about checking the values. Currently, the API key is one of the very few keys where we check if they're not empty. If we keep that, we should also check keys like the server_url. And potentially do much more validation...
However, improve configuration validation is not probably highest on our priority list. We could also leave it at simply improving the error message and create a separate issue to improve configuration validation to pick up down the road.

**Comment by bartvanb** [comment]
We decided to remove the validation for the API key. Also created #271 to handle validators properly at some point in the future.
