### ISSUE TITLE
[Bug] Setup.py is missing the README files

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#263]
**Describe the bug**
When installing the individual packages (common, server, node, etc.) There are still references to the README files that where at the package level. They have been removed in favor of the github top level README.

**To Reproduce**
1. clone repo
2. install package a package, e.g.: `pip install -e vantage6-common`
3. observe the error 

```
cd vantage6-common && pip install -e .
Obtaining file:///C:/Users/FMa1805.36838/Repositories/vantage6/vantage6-common
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\FMa1805.36838\Repositories\vantage6\vantage6-common\setup.py", line 11, in <module>
          with codecs.open(path.join('/..', here, 'README.md'), encoding='utf-8') as f:
        File "C:\tools\miniconda3\envs\socket\lib\codecs.py", line 904, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\FMa1805.36838\\Repositories\\vantage6\\vantage6-common\\README.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile:51: install-dev] Error 1
```

**Expected behavior**
Install without errors

**Comment by frankcorneliusmartin** [comment]
Already fixed in another PR
