### ISSUE TITLE
[Bug] `RuntimeError: Working outside of request context` when using encryption

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#305]
**Describe the bug**
I'm currently unable to use my algorithms in encrypted collaborations.
Whenever the algorithm tries to call the vantage6 api through the proxy I get the following error:
```
2022-09-08 11:28:29 - vantage6.node.proxy_server - ERROR    - Exception on /task [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 262, in proxy_task
    data["organizations"] = [future.result() for future in futures]
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 262, in <listcomp>
    data["organizations"] = [future.result() for future in futures]
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 159, in encrypt_input
    response = make_request('get', f'organization/{organization_id}')
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 104, in make_request
    method = get_method(request.method)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/flask/globals.py", line 33, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

**To Reproduce**
1. Create a collaboration with encrypted enabled
2. Make sure the nodes have `encrypted: true` in their config
3. Run an algorithm that makes use of the proxy, I used my [n2n diagnosics](https://github.com/CARRIER-project/v6-node-to-node-diagnostics)

**Expected behavior**
I expected the algorithm to run without error like it has done before

**Screenshots**

**Details**
- v6 version: 3.3.2 (although I had it on 3.0.2 as well)

**Additional context**
More of the log:
```
2022-09-08 11:28:28 - task_manager   - INFO     - Run docker image=harbor.carrier-mu.src.surf-hosted.nl/carrier/n2n-diagnostics:test
2022-09-08 11:28:28 - client         - DEBUG    - Making request: DELETE | https://v6server.carrier-mu.src.surf-hosted.nl:443/api/port | {'result_id': 19}
2022-09-08 11:28:28 - client         - DEBUG    - Making request: POST | https://v6server.carrier-mu.src.surf-hosted.nl:443/api/port | None
2022-09-08 11:28:29 - client         - DEBUG    - Making request: PATCH | https://v6server.carrier-mu.src.surf-hosted.nl:443/api/node/2 | None
2022-09-08 11:28:29 - node           - INFO     - Waiting for new tasks....
2022-09-08 11:28:29 - proxy_server   - DEBUG    - 2 organizations, attemping to encrypt
2022-09-08 11:28:29 - client         - DEBUG    - Making request: GET | https://v6server.carrier-mu.src.surf-hosted.nl:443/api/collaboration/1 | None
2022-09-08 11:28:29 - proxy_server   - DEBUG    - Retrieving public key of org: 3
2022-09-08 11:28:29 - proxy_server   - DEBUG    - Retrieving public key of org: 4
2022-09-08 11:28:29 - vantage6.node.proxy_server - ERROR    - Exception on /task [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 262, in proxy_task
    data["organizations"] = [future.result() for future in futures]
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 262, in <listcomp>
    data["organizations"] = [future.result() for future in futures]
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 159, in encrypt_input
    response = make_request('get', f'organization/{organization_id}')
  File "/vantage6/vantage6-node/vantage6/node/proxy_server.py", line 104, in make_request
    method = get_method(request.method)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/flask/globals.py", line 33, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
172.18.0.4 - - [2022-09-08 11:28:29] "POST /task HTTP/1.1" 500 426 0.128376
2022-09-08 11:28:30 - docker_manager - DEBUG    - Result id=19 is finished
2022-09-08 11:28:30 - task_manager   - ERROR    - Received non-zero exitcode: 1
2022-09-08 11:28:30 - task_manager   - ERROR    -   Container id: b4a0437e54e0c82d2d2dbbdb81533647decd53828d332069c9c1c8cd7d15d495
2022-09-08 11:28:30 - task_manager   - INFO     - info > wrapper for n2n_diagnostics
info > Reading input file /mnt/data/task-000000019/input
info > No data format specified. Assuming input data is pickle format
info > Reading token file '/mnt/data/task-000000019/token'
info > Using '/mnt/data/default.csv' as database
info > Dispatching ...
info > Module 'n2n_diagnostics' imported!
info > Running a master-container
info > Working with collaboration_id <1>
info > Defining input parameters
info > Dispatching node-tasks to organizations [3, 4]
Server responded with error code: 500
Did not find a message from the server
info > Exception!
info > Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/n2n_diagnostics/primary.py", line 29, in echo
    return try_echo(client, other_nodes)
  File "/opt/conda/lib/python3.9/site-packages/n2n_diagnostics/primary.py", line 53, in try_echo
    task = client.create_new_task(input_={'method': ECHO_TASK}, organization_ids=other_nodes)
  File "/opt/conda/lib/python3.9/site-packages/vantage6/client/__init__.py", line 1983, in create_new_task
    return self.post_task(
  File "/opt/conda/lib/python3.9/site-packages/vantage6/client/__init__.py", line 2042, in post_task
    return self.request('task', method='post', json={
  File "/opt/conda/lib/python3.9/site-packages/vantage6/client/__init__.py", line 211, in request
    self.refresh_token()
  File "/opt/conda/lib/python3.9/site-packages/vantage6/client/__init__.py", line 1905, in refresh_token
    raise Exception("Containers cannot refresh!")
Exception: Containers cannot refresh!

warn > Error encountered while calling echo: Containers cannot refresh!

2022-09-08 11:28:31 - node           - INFO     - Sending result (id=19) to the server!
2022-09-08 11:28:31 - client         - DEBUG    - Making request: GET | https://v6server.carrier-mu.src.surf-hosted.nl:443/api/result/19 | None
2022-09-08 11:28:31 - node           - CRITICAL - A container on a node within your collaboration part of run_id=19 has exited with a non-zero status_code
```

**Comment by frankcorneliusmartin** [comment]
Harukas version also needs to be checked as it uses the same local proxy server code

**Comment by frankcorneliusmartin** [comment]
Used the `copy_current_request_context` to copy the request context into the threaded function

**Comment by frankcorneliusmartin** [comment]
We are running in the same issue as described here: 

https://stackoverflow.com/questions/50585496/popped-wrong-app-context-when-using-gevent-spawn

**Comment by frankcorneliusmartin** [comment]
For now the multithread encryption module is disabled. Lets find some time to properly implement and test this feature.
