### ISSUE TITLE
[Bug]`change_my_password` function not working. 

### ISSUE THREAD

**Issue by stefan-wolfsheimer** [vantage6/vantage6#333]
**Describe the bug**
Change my password from the python client yields a 404 error.
 
**To Reproduce**
1. Configure the python client
2. Authenticate
3. Call change_my_password:
```
client.util.change_my_password(orig_pw, new_pw)
```
5. Observe errors in client and server logs:
```
2022-10-05 14:52:40 - token          - DEBUG    - Authenticate user using username and password
2022-10-05 14:52:40 - token          - INFO     - Trying to login 'root'
2022-10-05 14:52:41 - token          - INFO     - Succesfull login from root
2022-10-05 14:52:42 - server         - WARNING  - HTTP Exception occured during request
2022-10-05 14:52:42 - server         - DEBUG    - Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/flask/ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/werkzeug/routing.py", line 2032, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Expected behavior**
Password of authenticated user changed. 

**Screenshots**

**Details**
- Vantage6 version: server and client:  3.3.6

**Comment by frankcorneliusmartin** [comment]
Hi @stefan-wolfsheimer thanks for reaching out. Fix has been implemented by @bartvanb and should have been released in `3.3.7`. 

Feel free te re-open this issue if this issue still persists.
