### ISSUE TITLE
[Bug] Creating new table does not succeed with PostgresQL

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#411]
**Describe the bug**
In v3.5 a new column is added to the database, but this doesn't work properly for our postgresDB

**To Reproduce**
1. Have a v3.4 server with PostgresDB
2. restart server to get v3.5 update
3. See error

**Expected behavior**
No error

**Actual error**
```
2022-11-30T09:49:02.645306047Z 2022-11-30 09:49:02 - base           - WARNING  - Adding column otp_secret to table user as it did not exist yet
2022-11-30T09:49:02.714507910Z Traceback (most recent call last):
2022-11-30T09:49:02.714546110Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
2022-11-30T09:49:02.715460424Z     cursor, statement, parameters, context
2022-11-30T09:49:02.715505825Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
2022-11-30T09:49:02.715906231Z     cursor.execute(statement, parameters)
2022-11-30T09:49:02.715937832Z psycopg2.errors.SyntaxError: syntax error at or near "user"
2022-11-30T09:49:02.715945232Z LINE 1: ALTER TABLE user ADD COLUMN otp_secret VARCHAR(32)
2022-11-30T09:49:02.715950232Z                     ^
2022-11-30T09:49:02.715962432Z 
2022-11-30T09:49:02.715975232Z 
2022-11-30T09:49:02.715980532Z The above exception was the direct cause of the following exception:
2022-11-30T09:49:02.715985232Z 
2022-11-30T09:49:02.716005333Z Traceback (most recent call last):
2022-11-30T09:49:02.716018033Z   File "/vantage6/vantage6-server/vantage6/server/wsgi.py", line 11, in <module>
2022-11-30T09:49:02.716373438Z     server_app = run_server(config_file, system_folders=False)
2022-11-30T09:49:02.716391139Z   File "/vantage6/vantage6-server/vantage6/server/__init__.py", line 477, in run_server
2022-11-30T09:49:02.716763244Z     allow_drop_all=allow_drop_all)
2022-11-30T09:49:02.716779945Z   File "/vantage6/vantage6-server/vantage6/server/model/base.py", line 107, in connect
2022-11-30T09:49:02.716837946Z     self.add_missing_columns()
2022-11-30T09:49:02.716863746Z   File "/vantage6/vantage6-server/vantage6/server/model/base.py", line 128, in add_missing_columns
2022-11-30T09:49:02.717323953Z     self.add_col_to_table(col, table_cls)
2022-11-30T09:49:02.717348153Z   File "/vantage6/vantage6-server/vantage6/server/model/base.py", line 186, in add_col_to_table
2022-11-30T09:49:02.717357754Z     'ALTER TABLE %s ADD COLUMN %s %s' % (tab_name, col_name, col_type)
2022-11-30T09:49:02.717365954Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2191, in execute
2022-11-30T09:49:02.718306868Z     return connection.execute(statement, *multiparams, **params)
2022-11-30T09:49:02.718332469Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 976, in execute
2022-11-30T09:49:02.718834876Z     return self._execute_text(object_, multiparams, params)
2022-11-30T09:49:02.718852477Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1151, in _execute_text
2022-11-30T09:49:02.719409185Z     parameters,
2022-11-30T09:49:02.719490786Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
2022-11-30T09:49:02.720040795Z     e, statement, parameters, cursor, context
2022-11-30T09:49:02.720054795Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
2022-11-30T09:49:02.720614204Z     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
2022-11-30T09:49:02.720630304Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
2022-11-30T09:49:02.721328115Z     raise exception
2022-11-30T09:49:02.721352715Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
2022-11-30T09:49:02.721549718Z     cursor, statement, parameters, context
2022-11-30T09:49:02.721566018Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
2022-11-30T09:49:02.721911623Z     cursor.execute(statement, parameters)
2022-11-30T09:49:02.721997525Z sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "user"
2022-11-30T09:49:02.722013925Z LINE 1: ALTER TABLE user ADD COLUMN otp_secret VARCHAR(32)
2022-11-30T09:49:02.722019925Z                     ^
2022-11-30T09:49:02.722309630Z 
2022-11-30T09:49:02.722315430Z [SQL: ALTER TABLE user ADD COLUMN otp_secret VARCHAR(32)]
2022-11-30T09:49:02.722323230Z (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by bartvanb** [comment]
This is basically due to implementation of #364 not working properly (for Postgres)
