### ISSUE TITLE
[Change Request] Better error message for `vnode attach` when no nodes are running

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#606]
**Description**
We get an unclear error when running `vnode attach` if no nodes are running:

```
Traceback (most recent call last):
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\Scripts\vnode-script.py", line 33, in <module>
    sys.exit(load_entry_point('vantage6', 'console_scripts', 'vnode')())
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\bbe2101.54580\projects\vantage6\vantage6-master\vantage6\vantage6\cli\node.py", line 626, in cli_node_attach
    name = q.select("Select the node you wish to inspect:",
  File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\vantage\lib\site-packages\questionary\prompts\select.py", line 121, in select
    raise ValueError("A list of choices needs to be provided.")
ValueError: A list of choices needs to be provided.
```

This should be improved to a message that says no nodes are running

**Comment by frankcorneliusmartin** [comment]
Tested
