### ISSUE TITLE
[Bug] Websocket connection continuesly dropping

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#638]
**Describe the bug**
The node keeps disconnecting and connecting. It seems that after a certain amount of reconnect events (by normal behavior) the node keeps disconnecting.

Some pieces of log that can be relevant: 

```python
2023-05-04 10:48:54 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:48:54 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:48:54 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:48:54 - node           - ERROR    - Ping thread had an exception
Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 815, in __socket_ping_worker
    self.socketIO.emit('ping', namespace='/tasks')
  File "/usr/local/lib/python3.10/site-packages/socketio/client.py", line 393, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: /tasks is not a connected namespace.
2023-05-04 10:48:55 - task_manager   - DEBUG    - Succeeded to pull image: harbor2.vantage6.ai/demo/health-ri-demo-arm
2023-05-04 10:48:55 - socket         - INFO     - (Re)Connected to the /tasks namespace
```

Lots of blocks with:
```python
2023-05-04 10:50:13 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:50:13 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:50:13 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:50:13 - engineio.client - WARNING  - WebSocket connection was closed, aborting
```

```
2023-05-04 10:50:17 - engineio.client - ERROR    - packet queue is empty, aborting
2023-05-04 10:50:17 - engineio.client - ERROR    - packet queue is empty, aborting
2023-05-04 10:50:17 - engineio.client - ERROR    - packet queue is empty, aborting
2023-05-04 10:50:17 - engineio.client - ERROR    - packet queue is empty, aborting
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - urllib3.connectionpool - WARNING  - Connection pool is full, discarding connection: petronas.vantage6.ai. Connection pool size: 10
2023-05-04 10:50:18 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:50:18 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:50:18 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:50:19 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-05-04 10:50:21 - socket         - INFO     - (Re)Connected to the /tasks namespace
```

This seems to repeat indefinitely.

**To Reproduce**
1. Start a node with a unstable internet (our demo kit + phone)

**Comment by frankcorneliusmartin** [comment]
We do no longer observe the issue
