### ISSUE TITLE
[Bug] Node not shutting down clean

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#649]
**Describe the bug**
```python
2023-05-10 09:45:00 - socket         - INFO     - Disconnected from the server
2023-05-10 09:45:00 - node           - ERROR    - Ping thread had an exception
Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 873, in __socket_ping_worker
    self.socketIO.emit('ping', namespace='/tasks')
  File "/usr/local/lib/python3.10/site-packages/socketio/client.py", line 393, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: /tasks is not a connected namespace.
2023-05-10 09:45:01 - vpn_manager    - DEBUG    - Stopping and removing the VPN client container
2023-05-10 09:45:05 - network_man..  - DEBUG    - Disconnecting vantage6-demo-a-user from network'vantage6-demo-a-user-net'
2023-05-10 09:45:07 - network_man..  - DEBUG    - Network vantage6-demo-a-user-net already exists. Deleting it.
2023-05-10 09:45:08 - node           - INFO     - Bye!
Exception in thread Thread-1 (print_log_worker):
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\vantage6\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\tools\miniconda3\envs\vantage6\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\fma1805.36838\repositories\vantage6\vantage6\vantage6\cli\node.py", line 1008, in print_log_worker
    for log in logs_stream:
  File "C:\tools\miniconda3\envs\vantage6\lib\site-packages\docker\types\daemon.py", line 32, in __next__
    return next(self._stream)
  File "C:\tools\miniconda3\envs\vantage6\lib\site-packages\docker\api\client.py", line 418, in <genexpr>
    gen = (data for (_, data) in gen)
  File "C:\tools\miniconda3\envs\vantage6\lib\site-packages\docker\utils\socket.py", line 95, in <genexpr>
    return ((STDOUT, frame) for frame in frames_iter_tty(socket))
  File "C:\tools\miniconda3\envs\vantage6\lib\site-packages\docker\utils\socket.py", line 128, in frames_iter_tty
    if len(result) == 0:
TypeError: object of type 'int' has no len()
```

**Comment by bartvanb** [comment]
I can't seem to reproduce this. Can you add details of when you see this? Do other errors need to occur to see this?

Side note: it may be related to [this issue](https://github.com/docker/docker-py/issues/3098) in docker SDK for python. In that case, updating docker dependency version would probably solve the issue
