### ISSUE TITLE
[Bug] VPN is not alway connected

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#656]
**Describe the bug**
Sometimes when I start a task, the VPN does not seem to be connected:

```python
2023-05-11 09:55:36 - node           - ERROR    - Could not get VPN IP: VPN is not connected!
Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/docker/vpn_manager.py", line 227, in get_vpn_ip
    vpn_interface = json.loads(vpn_interface)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 907, in run_forever
    self.__start_task(taskresult)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 336, in __start_task
    task_status, vpn_ports = self.__docker.run(
  File "/vantage6/vantage6-node/vantage6/node/docker/docker_manager.py", line 428, in run
    vpn_ports = task.run(
  File "/vantage6/vantage6-node/vantage6/node/docker/task_manager.py", line 218, in run
    vpn_ports = self._run_algorithm()
  File "/vantage6/vantage6-node/vantage6/node/docker/task_manager.py", line 272, in _run_algorithm
    vpn_ports = self.__vpn_manager.forward_vpn_traffic(
  File "/vantage6/vantage6-node/vantage6/node/docker/vpn_manager.py", line 254, in forward_vpn_traffic
    ports = self._forward_traffic_to_algorithm(
  File "/vantage6/vantage6-node/vantage6/node/docker/vpn_manager.py", line 336, in _forward_traffic_to_algorithm
    vpn_ip = self.get_vpn_ip()
  File "/vantage6/vantage6-node/vantage6/node/docker/vpn_manager.py", line 231, in get_vpn_ip
    raise ConnectionError(
ConnectionError: Could not get VPN IP: VPN is not connected!
```

Usually waiting a bit and then running again solves the issue.  Seems to happen when I simulate a disconnect from the vantage6-server (by just restarting it)

I seem to be able to get it consistently to have a VPN node start up and immediately start a task.

**Comment by frankcorneliusmartin** [comment]
In the VPN container we observe restarts:

```python
2023-05-11 16:43:25 2023-05-11 14:43:25 [vpn.vantage6.ai] Inactivity timeout (--ping-restart), restarting
2023-05-11 16:43:25 2023-05-11 14:43:25 /sbin/ip route del 0.0.0.0/1
2023-05-11 16:43:25 2023-05-11 14:43:25 /sbin/ip route del 128.0.0.0/1
2023-05-11 16:43:25 2023-05-11 14:43:25 Closing TUN/TAP interface
2023-05-11 16:43:25 2023-05-11 14:43:25 /sbin/ip addr del dev tun0 10.76.0.188/16
2023-05-11 16:43:25 2023-05-11 14:43:25 SIGUSR1[soft,ping-restart] received, process restarting
2023-05-11 16:43:25 2023-05-11 14:43:25 Restart pause, 1 second(s)
2023-05-11 16:43:26 2023-05-11 14:43:26 TCP/UDP: Preserving recently used remote address: [AF_INET6]::ffff:20.56.168.145:443
2023-05-11 16:43:26 2023-05-11 14:43:26 Socket Buffers: R=[131072->131072] S=[16384->16384]
2023-05-11 16:43:26 2023-05-11 14:43:26 Attempting to establish TCP connection with [AF_INET6]::ffff:20.56.168.145:443
2023-05-11 16:43:26 2023-05-11 14:43:26 TCP connection established with [AF_INET6]::ffff:20.56.168.145:443
2023-05-11 16:43:26 2023-05-11 14:43:26 Socket flags: TCP_NODELAY=1 succeeded
2023-05-11 16:43:26 2023-05-11 14:43:26 TCPv6_CLIENT link local: (not bound)
2023-05-11 16:43:26 2023-05-11 14:43:26 TCPv6_CLIENT link remote: [AF_INET6]::ffff:20.56.168.145:443
2023-05-11 16:43:26 2023-05-11 14:43:26 TLS: Initial packet from [AF_INET6]::ffff:20.56.168.145:443, sid=3d63ac2b 8bae9635
2023-05-11 16:43:26 2023-05-11 14:43:26 VERIFY OK: depth=1, CN=VPN CA
2023-05-11 16:43:26 2023-05-11 14:43:26 VERIFY KU OK
```
