### ISSUE TITLE
[Bug] `client.run.get(.)` returns an error `str` object has no attribute `decode`

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#836]
**Describe the bug**
These function produce errors.

`client.run.get(.)` (also `client.run.list(.)` fails in this case)

RUN
-----
`client.run.get(1)` results in:

```python
--> Attempting to decrypt results!
Making request: GET | http://localhost:5000/api/run/1 | {}
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "GET /api/run/1 HTTP/1.1" 200 498
Invalid base64-encoded string: number of data characters (9) cannot be 1 more than a multiple of 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\diagnostic\lib\site-packages\vantage6\client\filter.py", line 93, in wrapper_filter
    dict_ = func(*args, **kwargs)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\diagnostic\lib\site-packages\vantage6\client\filter.py", line 178, in wrapper_filter
    return func(*args, **kwargs)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\diagnostic\lib\site-packages\vantage6\client\__init__.py", line 1336, in get
    run = self._decrypt_input(run_data=run, is_single_run=True)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\diagnostic\lib\site-packages\vantage6\client\__init__.py", line 1457, in _decrypt_input
    return self.parent._decrypt_field(
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\diagnostic\lib\site-packages\vantage6\common\client\client_base.py", line 460, in _decrypt_field
    data[field] = self._decrypt_input(data[field]).decode(
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

We can observe that the input is not correctly encoded using:
```python
>>> client.request('run/1')
Making request: GET | http://localhost:5000/api/run/1 | None
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "GET /api/run/1 HTTP/1.1" 200 498
{'node': {'ip': None, 'name': 'org_1 - demo Node', 'status': 'online', 'id': 2}, 'assigned_at': '2023-09-12T11:31:20.180235', 'task': {'id': 1, 'link': '/api/task/1', 'methods': ['DELETE', 'GET']}, 'results': {'id': 1, 'link': '/api/result/1', 'methods': ['GET', 'PATCH']}, 'ports': [], 'started_at': '2023-09-13T06:09:51.970115', 'finished_at': None, 'input': 'something', 'status': None, 'organization': {'id': 1, 'link': '/api/organization/1', 'methods': ['PATCH', 'GET']}, 'log': None, 'id': 1}
```

The `input` field is not properly encoded (base64). That explains that error. I think this happend through the `vserver import`. So two things need to be fixed:

1. update the `vserver import` command to encode the input properly
2. The `client.run.get()` and `client.run.list()` methods should be robust to unexpected values in these fields. (And print an error)

**Details**
 - version 4.0.0a7

**Comment by frankcorneliusmartin** [comment]
Still fails for the case the input / output is not properly encoded.
 
`vserver import` still imports plain str object into the db. 
maybe add an try except block to the decoding.
