### ISSUE TITLE
[Bug] `vnode-local` command raises exception

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#839]
**Describe the bug**
When I call `vnode-local` i get the following exception:
```python 
Traceback (most recent call last):
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\Scripts\vnode-local-script.py", line 33, in <module>
    sys.exit(load_entry_point('vantage6-node', 'console_scripts', 'vnode-local')())
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\Scripts\vnode-local-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\users\fma1805.36838\repositories\vantage6\vantage6-node\vantage6\node\__init__.py", line 57, in <module>
    from vantage6.common.client.node_client import NodeClient
  File "c:\users\fma1805.36838\repositories\vantage6\vantage6-common\vantage6\common\client\node_client.py", line 12, in <module>
    from vantage6.common.client.client_base import ClientBase
  File "c:\users\fma1805.36838\repositories\vantage6\vantage6-common\vantage6\common\client\client_base.py", line 10, in <module>
    from vantage6.common.encryption import RSACryptor, DummyCryptor
  File "c:\users\fma1805.36838\repositories\vantage6\vantage6-common\vantage6\common\encryption.py", line 25, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes
ImportError: cannot import name 'PrivateKeyTypes' from 'cryptography.hazmat.primitives.asymmetric.types' (C:\Users\FMa1805.36838\AppData\Local\miniconda3\lib\site-packages\cryptography\hazmat\primitives\asymmetric\types.py)
```

**To Reproduce**
1. `pip install vantage6-server==4.0.0a8`
2. run `vnode`

**Details**
 - Version 4.0.0a8

**Comment by bartvanb** [comment]
No longer the case with current version (4.1.1)
