### ISSUE TITLE
[Bug] Wrapper requires preprocessing to be defined and python client needs to specify both 'type' AND 'function' to be set

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#841]
**Describe the bug**
The wrapper crashes when no preprocessing is defined by the user with the `databases` argument. 

1. preprocessing is required (it should not)
```python
info > Using '/mnt/data/default.csv' with label 'default' as database
info > Applying preprocessing for database 'default'
error > Error encountered while calling partial_average: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/wrap.py", line 108, in _run_algorithm_method
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/decorators.py", line 144, in decorator
    preprocess = json.loads(
  File "/usr/local/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
error > None
```

2. both `type` and `function` need to be specified, likely to be related to #834 
The wrapper expect `function` to be set, while the API expect `type` to be set

This works:

```python
client.task.create(name='test', description='', image='harbor2.vantage6.ai/demo/average:4.0.0a6', collaboration=1, organizations=[1], input_={'master':1, 'method': 'central_average', 'kwargs': {'column_name': 'age'}}, databases=[{'label': 'default', "preprocessing": [{'type': 'filter_range', "function": "filter_range", "parameters": {"column": "age", "min_": 0, "max_": 100}}]}])
```
**Details**
 - Version 4.0.0a8

**Comment by frankcorneliusmartin** [comment]
✅ Checked in v4.0.0a10

Note that in case you do not supply a database while it expects one you get the misleading error: 
`error > Error encountered while calling partial_average: '_DATABASE_URI'`
