### ISSUE TITLE
[Bug] `vdev create-demo-network` tries to reach weird file locations

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#856]
**Describe the bug**
When I try the `vdev create-demo-network` command I get errors because the program wants to create files in locations it doesn't have permissions for. I've tried this with both version 3.11.1 and 4.0.0. The errors are slightly different but it is both about reaching directories that it doesn't have permissions for. Vdev has no business sniffing around in those file locations if you ask me.

The error in 3.11.1. For context, `i3` is my window manager, it has nothing to do with v6:
```shell
 vdev-test vdev create-demo-network
? Please enter a configuration-name: vdev-test2
[info ] - Spawned dataset for vdev-test2_node_1, writing to /home/dsmits/.config/vantage6/dev/vdev-test2/df_vdev-test2_node_1.csv
[info ] - Spawned node for organization 1
[info ] - Spawned dataset for vdev-test2_node_2, writing to /home/dsmits/.config/vantage6/dev/vdev-test2/df_vdev-test2_node_2.csv
[info ] - Spawned node for organization 2
[info ] - Spawned dataset for vdev-test2_node_3, writing to /home/dsmits/.config/vantage6/dev/vdev-test2/df_vdev-test2_node_3.csv
[info ] - Spawned node for organization 3
[info ] - Organization 1 is the admin
[info ] - Server import configuration ready, writing to /home/dsmits/.config/vantage6/dev/vdev-test2.yaml
[info ] - Server configuration read, writing to /etc/xdg/xdg-i3/vantage6/server/vdev-test2.yaml
[info ] - Created 3 node configuration(s), attaching them to vdev-test2.
[info ] - Starting server...
[info ] - Finding Docker daemon.
[info ] - Pulling latest server image 'harbor2.vantage6.ai/infrastructure/server:petronas'.
[info ] -  ... success!
[info ] - Creating mounts
Traceback (most recent call last):
  File "/home/dsmits/mambaforge/envs/v6-local/bin/vdev", line 8, in <module>
    sys.exit(cli_dev())
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/site-packages/vantage6/cli/dev.py", line 336, in create_demo_network
    vserver_import(ctx, server_import_config, False, image, '', False)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/site-packages/vantage6/cli/server.py", line 560, in vserver_import
    os.makedirs(dirname, exist_ok=True)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/dsmits/mambaforge/envs/v6-local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/i3'
```

In 4.0.0
```shell
(v6-4) ➜  vdev-test vdev create-demo-network
? Please enter a configuration-name: vdev3
[info ] - Spawned dataset for vdev3_node_1, writing to /home/dsmits/.config/vantage6/dev/vdev3/df_vdev3_node_1.csv
[info ] - Spawned node for organization 1
[info ] - Spawned dataset for vdev3_node_2, writing to /home/dsmits/.config/vantage6/dev/vdev3/df_vdev3_node_2.csv
[info ] - Spawned node for organization 2
[info ] - Spawned dataset for vdev3_node_3, writing to /home/dsmits/.config/vantage6/dev/vdev3/df_vdev3_node_3.csv
[info ] - Spawned node for organization 3
[info ] - Organization 1 is the admin
[info ] - Server import configuration ready, writing to /home/dsmits/.config/vantage6/dev/vdev3.yaml
Traceback (most recent call last):
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/vantage6/server/vdev3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/vantage6/server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsmits/mambaforge/envs/v6-4/bin/vdev", line 8, in <module>
    sys.exit(cli_dev())
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/site-packages/vantage6/cli/dev.py", line 339, in create_demo_network
    demo = demo_network(num_nodes, server_url, server_port, server_name)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/site-packages/vantage6/cli/dev.py", line 303, in demo_network
    server_config = create_vserver_config(server_name, server_port)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/site-packages/vantage6/cli/dev.py", line 261, in create_vserver_config
    config_dir.mkdir(parents=True, exist_ok=True)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/dsmits/mambaforge/envs/v6-4/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/etc/vantage6'
```

As you can see, the configuration files are placed within my home directory, so I don't understand what it's trying to do in the other locations.

**To Reproduce**
```shell
 vdev-test vdev create-demo-network
```

**Screenshots**

**Details**
 - OS: Ubuntu 22.04
 - Version 3.11.1 and Version 4.0.0

**Comment by bartvanb** [comment]
Hi @dsmits, I think the error in v4 is caused because in v4, we store vantage6 server config files in `/etc/vantage6/` instead of `/etc/xdg/` to conform to Linux Filesystem standard (#269). But I think you need to create `/etc/vantage6/` first with sudo. Could you test that? I guess we may need to fix that or improve the error message.

**Comment by bartvanb** [comment]
@dsmits could you check the above?

**Comment by ivanzhovannik** [comment]
I think this is not the only directory, which creates troubles during `vdev create-demo-network` @bartvanb @dsmits 

I have some issues with root '/Library/Application Support' - why don't we do it on a user level?

```
/etc % vdev create-demo-network
? Please enter a configuration-name: dummy_v6_network
[info ] - Spawned dataset for dummy_v6_network_node_1, writing to /Users/ivanzhovannik/Library/Application Support/vantage6/dev/dummy_v6_network/df_dummy_v6_network_node_1.csv
[info ] - Spawned node for organization 1
[info ] - Spawned dataset for dummy_v6_network_node_2, writing to /Users/ivanzhovannik/Library/Application Support/vantage6/dev/dummy_v6_network/df_dummy_v6_network_node_2.csv
[info ] - Spawned node for organization 2
[info ] - Spawned dataset for dummy_v6_network_node_3, writing to /Users/ivanzhovannik/Library/Application Support/vantage6/dev/dummy_v6_network/df_dummy_v6_network_node_3.csv
[info ] - Spawned node for organization 3
[info ] - Organization 1 is the admin
[info ] - Server import configuration ready, writing to /Users/ivanzhovannik/Library/Application Support/vantage6/dev/dummy_v6_network.yaml
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Application Support/vantage6/server/dummy_v6_network'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Application Support/vantage6/server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/bin/vdev", line 8, in <module>
    sys.exit(cli_dev())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/vantage6/cli/dev/create.py", line 315, in create_demo_network
    demo = demo_network(num_nodes, server_url, server_port, server_name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/vantage6/cli/dev/create.py", line 284, in demo_network
    server_config = create_vserver_config(server_name, server_port)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/site-packages/vantage6/cli/dev/create.py", line 242, in create_vserver_config
    config_dir.mkdir(parents=True, exist_ok=True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/km_env/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Library/Application Support/vantage6'
```

**Comment by ivanzhovannik** [comment]
And even after creating all the directories with sudo, it cannot reach docker engine, although it is up and running other v6 nodes:

```

sudo vdev start-demo-network
? Select the configuration you want to use: dummy-v6-net             
Cannot reach the Docker engine! Please make sure Docker is running.
Exiting...
```

```
docker ps 
CONTAINER ID   IMAGE                                              COMMAND                  CREATED              STATUS              PORTS              NAMES
d0bfcec6c618   harbor2.vantage6.ai/infrastructure/node:cotopaxi   "vnode-local start -…"   About a minute ago   Up About a minute   80/tcp, 2222/tcp   vantage6-dummy-v6-net_node_2-user
```

how does vdev understand, which docker engine to use?

**Comment by frankcorneliusmartin** [comment]
@ivanzhovannik Do other commands also fail for you? Like `v6 node start`? We use the function `from_env` from the docker-py libary, see here: https://docker-py.readthedocs.io/en/stable/client.html#docker.client.from_env

**Comment by frankcorneliusmartin** [comment]
I encountered the same issues as @dsmits today.

I both created the folders: 
- `/usr/local/share/vantage6`
- `/usr/local/share/vantage6/server`

Then changed the owner of  `/usr/local/share/vantage6/server` to my current user

**Comment by ivanzhovannik** [comment]
Regular v6 commands work just fineВт, 23 янв. 2024 г. в 10:54, Frank Martin ***@***.***>:
@ivanzhovannik Do other commands also fail for you? Like v6 node start? We use the function from_env from the docker-py libary, see here: https://docker-py.readthedocs.io/en/stable/client.html#docker.client.from_env

**Comment by frankcorneliusmartin** [comment]
> Regular v6 commands work just fine @frankcorneliusmartin

I am surprised. Today I was testing on a Mac and encountered indeed that is trying to use `'/Library/Application Support'` for the server configuration files. However in my case it is consistent behaviour as ` v6 server create` will also use this directory. 

We use the package [appdirs](https://github.com/ActiveState/appdirs) (I just noticed the project is dead, so maybe this is a good moment to use a different library to select the dirs) to determine which directories to use on the different OSs. 

On MacOS I was not able to use the system directories at all as when Docker started the container the mount to the config file generated an error (most likely due to the space in `Application Support`.

**Comment by frankcorneliusmartin** [comment]
@dsmits can you confirm that this is no longer an issue?

**Comment by bartvanb** [comment]
This must be resolved by now because `v6 dev` now puts the configurations by default in the user directories
