### ISSUE TITLE
[Bug] Server does not initialize properly if multiple instances are running

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#861]
**Describe the bug**
When the server is started for the first time, it initializes the database. Apart from creating the tables, it also creates a number of default roles, the root user, and the root organization.

When we have multiple server instances running (with RabbitMQ to connect the socket channels), it can happen that multiple instances try to initialize the database at the same time. This leads to errors (e.g. organization names are not unique if one tries to create 'root' organization twice) and to double database records (e.g. for default roles, as roles are allowed to have the same name).

**To Reproduce**
1. Create a horizontally scaled server (e.g. with App Service on Azure)
2. Start up the server for the first time
3. See the log issues.

**Expected behavior**
Database records are created by only one server instance. Probably, this instance claims the database while setting up.

**Example error**
```
2023-09-21T09:59:12.829704912Z The above exception was the direct cause of the following exception:
2023-09-21T09:59:12.829711812Z 
2023-09-21T09:59:12.829716812Z Traceback (most recent call last):
2023-09-21T09:59:12.829723312Z   File "/vantage6/vantage6-server/vantage6/server/wsgi.py", line 15, in <module>
2023-09-21T09:59:12.829854115Z     server_app = run_server(config_file, system_folders=False)
2023-09-21T09:59:12.829874515Z   File "/vantage6/vantage6-server/vantage6/server/__init__.py", line 676, in run_server
2023-09-21T09:59:12.830242522Z     return ServerApp(ctx).start()
2023-09-21T09:59:12.830257722Z   File "/vantage6/vantage6-server/vantage6/server/__init__.py", line 621, in start
2023-09-21T09:59:12.830605929Z     user.save()
2023-09-21T09:59:12.830756731Z   File "/vantage6/vantage6-server/vantage6/server/model/base.py", line 374, in save
2023-09-21T09:59:12.830909734Z     session.commit()
2023-09-21T09:59:12.830923335Z   File "<string>", line 2, in commit
2023-09-21T09:59:12.831402743Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
2023-09-21T09:59:12.831923953Z     self._transaction.commit(_to_root=self.future)
...
2023-09-21T09:59:12.839555694Z     self.dialect.do_execute(
2023-09-21T09:59:12.839573495Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-09-21T09:59:12.839912801Z     cursor.execute(statement, parameters)
2023-09-21T09:59:12.840024203Z sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "organization_name_key"
2023-09-21T09:59:12.840184306Z DETAIL:  Key (name)=(root) already exists.
```

**Comment by bartvanb** [comment]
Idea: maybe we can solve this by locking the database connection from a single instance and waiting in the other instances

**Comment by bartvanb** [comment]
This is fixed in v5
