### ISSUE TITLE
[Bug] `vdev start-demo-network` does not check if the container name is free

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#880]
**Describe the bug**
```python
vdev start-demo-network
? Select the configuration you want to use: omop
[info ] - Starting server...
[info ] - Finding Docker daemon.
[info ] - Pulling latest server image 'harbor2.vantage6.ai/infrastructure/server:cotopaxi'.
[debug] - Local image is up-to-date: harbor2.vantage6.ai/infrastructure/server:cotopaxi
[info ] -  ... success!
[info ] - Creating mounts
[warn ] - Message queue disabled! This means that the vantage6 server cannot be scaled horizontally!
[info ] - Run Docker container
Traceback (most recent call last):
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\docker\api\client.py", line 268, in _raise_for_status
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.43/containers/create?name=vantage6-omop-system-server

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\Scripts\vdev.exe\__main__.py", line 7, in <module>
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\vantage6\cli\server.py", line 106, in func_with_context
    return func(ctx, *args, **kwargs)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\vantage6\cli\dev.py", line 374, in start_demo_network
    vserver_start(
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\vantage6\cli\server.py", line 309, in vserver_start
    container = docker_client.containers.run(
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\docker\models\containers.py", line 858, in run
    container = self.create(image=image, command=command,
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\docker\models\containers.py", line 917, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\docker\api\container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\docker\api\container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\docker\api\client.py", line 274, in _result
    self._raise_for_status(response)
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\docker\api\client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "C:\Users\FMa1805.36838\AppData\Local\miniconda3\envs\cotopaxi\lib\site-packages\docker\errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 409 Client Error for http+docker://localnpipe/v1.43/containers/create?name=vantage6-omop-system-server: Conflict ("Conflict. The container name "/vantage6-omop-system-server" is already in use by container "1825ab1ee77346533db094123bc882b9b97df368c9688842a1aa84d39afa8960". You have to remove (or rename) that container to be able to reuse that name.")
```

**Expected behavior**
Not this exception, so remove it or give a better error message `docker rm /vantage6-omop-system-server` fixes the issue

**Details**
 - Version 4.0.0

**Comment by bartvanb** [comment]
Closing this as this command is removed in v5
