### ISSUE TITLE
[Bug] socketio.exceptions.BadNamespaceError: /tasks is not a connected namespace.

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#886]
**Describe the bug**
In Vantage6 4.0.0 every now and then when I start the node I get and error about namespace /tasks:

```
2023-10-03 07:48:06 - node           - INFO     - Waiting for new tasks....
2023-10-03 07:48:11 - node           - ERROR    - Ping thread had an exception
Traceback (most recent call last):
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 937, in __socket_ping_worker
    self.socketIO.emit('ping', namespace='/tasks')
  File "/usr/local/lib/python3.10/site-packages/socketio/client.py", line 393, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: /tasks is not a connected namespace.
```

It is fixed by restarting the node. Then I get:
```
2023-10-03 07:50:05 - node           - INFO     - Waiting for new tasks....
2023-10-03 07:50:05 - socket         - INFO     - Node xx
2023-10-03 07:50:05 - socket         - INFO     - Node xx
2023-10-03 07:50:05 - socket         - INFO     - (Re)Connected to the /tasks namespace
```

**To Reproduce**
No idea how to reproduce it, it happens up to 50% of the time I start a node.

**Expected behavior**
No error

**Comment by bartvanb** [comment]
This is likely due to the same issue as #887 which is solved now
