### ISSUE TITLE
[Bug] SQL / session errors on non-local v4 servers

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#887]
**Describe the bug**

There are SQLAlchemy issues with deployed v4 vantage6 servers:

- Only when deployed (Azure / PostGresQL)
- Only seems to occur when the user disconnects their socket connection **while the request is being executed**

Endpoints where I see the error:
- POST task
- GET task
- PATCH run
- DELETE task

Also, error occurs upon
- ```engineio.server - ERROR    - message handler error```

Full traceback example
```
2023-10-03T08:05:45.070512080Z 2023-10-03 08:05:45 - server         - DEBUG    - Received request: POST task
2023-10-03T08:05:45.446580880Z 2023-10-03 08:05:45 - resource       - DEBUG    - Received request from user <user> (3)
2023-10-03T08:05:45.752308646Z 2023-10-03 08:05:45 - task           - DEBUG    - New job_id 2
2023-10-03T08:05:45.964735770Z 2023-10-03 08:05:45 - websockets     - INFO     - <user> left room collaboration_1
2023-10-03T08:05:46.097219932Z 2023-10-03 08:05:46 - websockets     - INFO     - <user> disconnected
2023-10-03T08:05:46.097784739Z 2023-10-03 08:05:46 - task           - DEBUG    - Assigning task to 1 nodes.
2023-10-03T08:05:46.226165446Z 2023-10-03 08:05:46 - task           - DEBUG    - Assigning task to <collab>.
2023-10-03T07:30:25.704070572Z 2023-10-03 07:30:25 - task           - INFO     - New task for collaboration 'AIOC'
2023-10-03T07:30:25.704867577Z 2023-10-03 07:30:25 - server         - ERROR    - Exception occured during request
2023-10-03T07:30:25.704905278Z Traceback (most recent call last):
2023-10-03T07:30:25.704911578Z   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023-10-03T07:30:25.704916678Z     rv = self.dispatch_request()
2023-10-03T07:30:25.704920678Z   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
2023-10-03T07:30:25.704924478Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-10-03T07:30:25.704928278Z   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-10-03T07:30:25.704932078Z     resp = resource(*args, **kwargs)
2023-10-03T07:30:25.704935378Z   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 107, in view
2023-10-03T07:30:25.704938778Z     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-10-03T07:30:25.704942278Z   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-10-03T07:30:25.704946378Z     resp = meth(*args, **kwargs)
2023-10-03T07:30:25.704949978Z   File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 154, in decorator
2023-10-03T07:30:25.704953878Z     return current_app.ensure_sync(fn)(*args, **kwargs)
2023-10-03T07:30:25.704957778Z   File "/vantage6/vantage6-server/vantage6/server/resource/__init__.py", line 241, in decorator
2023-10-03T07:30:25.704961978Z     return fn(*args, **kwargs)
2023-10-03T07:30:25.704965378Z   File "/vantage6/vantage6-server/vantage6/server/resource/task.py", line 649, in post
2023-10-03T07:30:25.704968978Z     log.debug(f" created by: '{g.user.username}'")
2023-10-03T07:30:25.704972878Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 482, in __get__
2023-10-03T07:30:25.704976878Z     return self.impl.get(state, dict_)
2023-10-03T07:30:25.704980678Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 942, in get
2023-10-03T07:30:25.704984478Z     value = self._fire_loader_callables(state, key, passive)
2023-10-03T07:30:25.704988378Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 973, in _fire_loader_callables
2023-10-03T07:30:25.704992378Z     return state._load_expired(state, passive)
2023-10-03T07:30:25.705006078Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 712, in _load_expired
2023-10-03T07:30:25.705010178Z     self.manager.expired_attribute_loader(self, toload, passive)
2023-10-03T07:30:25.705014078Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 1369, in load_scalar_attributes
2023-10-03T07:30:25.705019578Z     raise orm_exc.DetachedInstanceError(
2023-10-03T07:30:25.705023478Z sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x789af444e440> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)
```

We also see:
```
2023-10-03T12:27:54.149441369Z Traceback (most recent call last):
2023-10-03T12:27:54.149673171Z   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2552, in __call__
2023-10-03T12:27:54.150439478Z     return self.wsgi_app(environ, start_response)
2023-10-03T12:27:54.150466578Z   File "/usr/local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
2023-10-03T12:27:54.150559079Z     return super(_SocketIOMiddleware, self).__call__(environ,
2023-10-03T12:27:54.150586679Z   File "/usr/local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
2023-10-03T12:27:54.151111484Z     return self.engineio_app.handle_request(environ, start_response)
2023-10-03T12:27:54.151130984Z   File "/usr/local/lib/python3.10/site-packages/socketio/server.py", line 605, in handle_request
2023-10-03T12:27:54.151138084Z     return self.eio.handle_request(environ, start_response)
2023-10-03T12:27:54.151166084Z   File "/usr/local/lib/python3.10/site-packages/engineio/server.py", line 409, in handle_request
2023-10-03T12:27:54.151512087Z     socket = self._get_socket(sid)
2023-10-03T12:27:54.151528788Z   File "/usr/local/lib/python3.10/site-packages/engineio/server.py", line 638, in _get_socket
2023-10-03T12:27:54.151592588Z     raise KeyError('Session is disconnected')
2023-10-03T12:27:54.151641188Z KeyError: 'Session is disconnected'
```

**Comment by bartvanb** [comment]
This seems to be resolved.

We made a configuration error in the server config file for cotopaxi.vantage6.ai:

Instead of 

```
rabbitmq:
  uri: the_uri
```

We still had the v3 version formatting

```
rabbitmq_uri: the_uri
```

And therefore horizontal scaling was not working which seems to have led to the variety of socket issues shown above.
