### ISSUE TITLE
[Bug] Node socket callback does not function in deployed conditions

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#891]
**Describe the bug**
When starting a node for v4.0.1, the new callback on the node is not properly handled:

```
2023-10-06 06:15:24 - socket         - INFO     - Node <root-test - root> joined room <collaboration_10_organization_1>
Exception in thread Thread-11 (_handle_eio_message):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/socketio/client.py", line 707, in _handle_eio_message
    self._handle_ack(pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.10/site-packages/socketio/client.py", line 606, in _handle_ack
    callback(*data)
TypeError: NodeTaskNamespace.authenticated_connection() missing 1 required positional argument: 'authenticated'
2023-10-06 06:17:30 - engineio.client - WARNING  - WebSocket connection was closed, aborting
2023-10-06 06:17:30 - socket         - INFO     - Disconnected from the server
```

**To Reproduce**
- have a deployed server
- start up a node in v4.0.1

**Expected behavior**
No errors - nodes should reconnect if JWT is invalid and sync if it is valid

**Comment by bartvanb** [comment]
Fixed by #892
