### ISSUE TITLE
[Bug] Encryption support in algorithm client is missing

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#955]
**Describe the bug**
When trying to run an algorithm such as [v6-average-py](https://github.com/IKNL/v6-average-py), it fails to produce results when running the `central_average()` method.

**To Reproduce**
1. Have a collaboration with 2 organizations: 2 nodes.
    With simple csv data. For example, this, which we will label `letters_test` for the database.
   ```csv
   id,value
   1,10
   2,20
   3,30
   ```
   and
   ```csv
   id,value
   5,50
   6,60
   7,70
   ```
2. Create a task:
    e.g.
    ```python
    average_task_aggregate = client.task.create(collaboration=4,
                                  organizations=[9],
                                  name="letters-test-aggregate-average-task",
                                  image="harbor2.vantage6.ai/demo/average",
                                  description='',
                                  databases=[
                                      {'label': 'letters_test'}
                                  ],
                                  input_=input_)
    ```
4. Check logs at the node
5. See error
    ```
    2023-12-19 14:58:12 - common         - DEBUG    - Sending algorithm run update to server
    2023-12-19 14:58:12 - common         - DEBUG    - Making request: PATCH | https://someserver.example.org:443/api/run/132 | None
    2023-12-19 14:58:15 - docker_manager - DEBUG    - Run id=131 is finished
    2023-12-19 14:58:15 - task (102)     - ERROR    - Received non-zero exitcode: 1
    2023-12-19 14:58:15 - task (102)     - ERROR    -   Container id: 00a8fba3104de47445efe5bbb73858eab855f9f040ebde8841bca77235df9353
    2023-12-19 14:58:15 - task (102)     - INFO     - info > wrapper for v6-average-py
    info > Reading input file /mnt/data/task-000000131/input
    info > Dispatching ...
    info > Module 'v6-average-py' imported!
    info > Reading token
    info > Collecting participating organizations
    info > Requesting partial computation
    info > Waiting for results
    info > Waiting for results of task 103...
    info > Waiting for results of task 103...
    info > Waiting for results of task 103...
    info > Waiting for results of task 103...
    info > Waiting for results of task 103...
    info > Done!
    Unable to load results
    info > Partial results are in!
    info > Computing global average
    error > Error encountered while calling central_average: division by zero
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/wrap.py", line 108, in _run_algorithm_method
        result = method(*args, **kwargs)
    error > None
      File "/usr/local/lib/python3.10/site-packages/vantage6/algorithm/tools/decorators.py", line 63, in wrap_function
        return func(client, *args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/v6-average-py/__init__.py", line 67, in central_average
        return {"average": global_sum / global_count}
    ZeroDivisionError: division by zero

    2023-12-19 14:58:15 - common         - DEBUG    - Making request: DELETE | https://someserver.example.org:443/api/port | {'run_id': 131}
    2023-12-19 14:58:15 - node           - INFO     - Sending result (run=131) to the server!
    2023-12-19 14:58:15 - common         - DEBUG    - Making request: GET | https://someserver.example.org:443/api/run/131 | None
    2023-12-19 14:58:15 - socket         - CRITICAL - A container on a node within your collaboration part of job_id=70 has exited with status crashed
    2023-12-19 14:58:15 - common         - DEBUG    - Making request: GET | https://someserver.example.org:443/api/task/102 | None
    ```
On the client side, the task fails to produce a result
```
Results object:
{'data': [{'result': '', 'id': 131, 'task': {'id': 102, 'link': '/api/task/102', 'methods': ['DELETE', 'GET']}, 'run': {'id': 131, 'link': '/api/run/131', 'methods': ['GET', 'PATCH']}}], 'links': {'first': '/api/result?task_id=102&page=1', 'self': '/api/result?task_id=102&page=1', 'last': '/api/result?task_id=102&page=1'}}
```

**Expected behavior**
The correct global average.

And, in general, I think it would be best if the algorithm developer didn't have to handle encryption themselves. 

**Details**
- Linux, plain docker
- Vantage6 version: 4.1.2.

**Comment by lsago** [comment]
There is a [comment in the code that indicates that the "_algorithm developer is responsible for decrypting the results_"](https://github.com/vantage6/vantage6/blob/2502eb6dcb60895aa69f3b48d007d21e9edb0586/vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py#L293-L294). But perhaps this plan was abandoned?

At least, I think it's reasonable to expect the function [`wait_for_results()`](https://github.com/vantage6/vantage6/blob/207f4840affc963a65ee55c0b08930207df15a2e/vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py#L122) in the algorithm wrapper to work even when encryption is enabled at the collaboration level.

I believe the error comes from [this line](https://github.com/vantage6/vantage6/blob/207f4840affc963a65ee55c0b08930207df15a2e/vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py#L299), where we find the following:
```python
            # Encryption is not done at the client level for the container. The
            # algorithm developer is responsible for decrypting the results.
            decoded_results = []
            try:
                decoded_results = [
                    json_lib.loads(
                        base64s_to_bytes(result.get("result")).decode()
                    )
                    for result in results if result.get("result")
                ]
```
We will base64 decode into bytes that are not necessarily a string, but a cipher-text bytes. Therefore, when trying to `.decode()` into utf-8, it will very likely fail.
