### ISSUE TITLE
[Bug] `Bad Request ("create .: volume name is too short, names should be at least two alphanumeric characters")` when starting node

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#971]
A while ago I installed a vantage6 server and node, version 3.3.7.

Since a month I run into the following issue when I try to start the node, this didn't happen before:

```
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.43/containers/create?name=vantage6-cbs-test-user: Bad Request ("create .: volume name is too short, names should be at least two alphanumeric characters")
```

Full log and stacktrace:
```
dsmits@cbsnode:/app$ sudo vnode start -c cbs-test.yaml --mount-src $PWD/code
[info]  - Starting node...
[info]  - Finding Docker daemon
[info]  - Checking that data and log dirs exist
[info]  - Pulling latest node image 'harbor2.vantage6.ai/infrastructure/node:3.3.7'
[debug] - Remote image is newer: harbor2.vantage6.ai/infrastructure/node:3.3.7
[debug] - Succeeded to pull image: harbor2.vantage6.ai/infrastructure/node:3.3.7
[info]  -  ... success!
[info]  - Creating Docker data volume
[info]  - Creating file & folder mounts
[info]  - Setting up databases
[info]  -   Processing database 'default:/app/diabetes.csv'
[debug] -   - file-based database added
[info]  - Running Docker container
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.43/containers/create?name=vantage6-cbs-test-user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/vnode", line 8, in <module>
    sys.exit(cli_node())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vantage6/cli/node.py", line 487, in cli_node_start
    container = docker_client.containers.run(
  File "/usr/local/lib/python3.10/dist-packages/docker/models/containers.py", line 819, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.10/dist-packages/docker/models/containers.py", line 878, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/container.py", line 439, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.43/containers/create?name=vantage6-cbs-test-user: Bad Request ("create .: volume name is too short, names should be at least two alphanumeric characters")

```

**Comment by frankcorneliusmartin** [comment]
Make sure to use absolute paths when specifying the configuration file. From the docs:
`-c, --config TEXT       Absolute path to configuration-file; overrides NAME`
